In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0"
}

In [3]:
url = "https://www.amazon.in/gp/bestsellers/"

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [4]:
soup = BeautifulSoup(response.text, "lxml")

print(soup.title.text)

Amazon.in Bestsellers: The most popular items on Amazon

In [5]:
category_links = soup.find_all("a")

print(len(category_links))

284

In [6]:
categories = []

for link in category_links:
    
    href = link.get("href")
    text = link.text.strip()
    
    if href and "/gp/bestsellers/" in href:
        
        full_link = "https://www.amazon.in" + href
        
        categories.append((text, full_link))

print(categories[:20])

[('Bestsellers', 'https://www.amazon.in/gp/bestsellers/?ref_=nav_cs_bestsellers'), ('Bestsellers', 'https://www.amazon.in/gp/bestsellers/ref=zg_bs_tab_bs'), ('Amazon Launchpad', 'https://www.amazon.in/gp/bestsellers/boost/ref=zg_bs_nav_boost_0'), ('Amazon Renewed', 'https://www.amazon.in/gp/bestsellers/amazon-renewed/ref=zg_bs_nav_amazon-renewed_0'), ('Apps & Games', 'https://www.amazon.in/gp/bestsellers/mobile-apps/ref=zg_bs_nav_mobile-apps_0'), ('Baby Products', 'https://www.amazon.in/gp/bestsellers/baby/ref=zg_bs_nav_baby_0'), ('Bags, Wallets and Luggage', 'https://www.amazon.in/gp/bestsellers/luggage/ref=zg_bs_nav_luggage_0'), ('Beauty', 'https://www.amazon.in/gp/bestsellers/beauty/ref=zg_bs_nav_beauty_0'), ('Books', 'https://www.amazon.in/gp/bestsellers/books/ref=zg_bs_nav_books_0'), ('Car & Motorbike', 'https://www.amazon.in/gp/bestsellers/automotive/ref=zg_bs_nav_automotive_0'), ('Clothing & Accessories', 'https://www.amazon.in/gp/bestsellers/apparel/ref=zg_bs_nav_apparel_0'), ('Computers & Accessories', 'https://www.amazon.in/gp/bestsellers/computers/ref=zg_bs_nav_computers_0'), ('Electronics', 'https://www.amazon.in/gp/bestsellers/electronics/ref=zg_bs_nav_electronics_0'), ('Garden & Outdoors', 'https://www.amazon.in/gp/bestsellers/garden/ref=zg_bs_nav_garden_0'), ('Gift Cards', 'https://www.amazon.in/gp/bestsellers/gift-cards/ref=zg_bs_nav_gift-cards_0'), ('Grocery & Gourmet Foods', 'https://www.amazon.in/gp/bestsellers/grocery/ref=zg_bs_nav_grocery_0'), ('Health & Personal Care', 'https://www.amazon.in/gp/bestsellers/hpc/ref=zg_bs_nav_hpc_0'), ('Home & Kitchen', 'https://www.amazon.in/gp/bestsellers/kitchen/ref=zg_bs_nav_kitchen_0'), ('Home Improvement', 'https://www.amazon.in/gp/bestsellers/home-improvement/ref=zg_bs_nav_home-improvement_0'), ('Industrial & Scientific', 'https://www.amazon.in/gp/bestsellers/industrial/ref=zg_bs_nav_industrial_0')]

In [7]:
unique_categories = {}

for name, link in categories:
    
    if name not in unique_categories:
        unique_categories[name] = link

print(len(unique_categories))

33

In [8]:
for name in unique_categories:
    print(name)

Bestsellers
Amazon Launchpad
Amazon Renewed
Apps & Games
Baby Products
Bags, Wallets and Luggage
Beauty
Books
Car & Motorbike
Clothing & Accessories
Computers & Accessories
Electronics
Garden & Outdoors
Gift Cards
Grocery & Gourmet Foods
Health & Personal Care
Home & Kitchen
Home Improvement
Industrial & Scientific
Jewellery
Kindle Store
Movies & TV Shows
Music
Musical Instruments
Office Products
Pet Supplies
Shoes & Handbags
Software
Sports, Fitness & Outdoors
Toys & Games
Video Games
Watches
See More

In [9]:
important_categories = [
    "Mobiles",
    "Amazon Renewed",
    "Electronics",
    "Computers & Accessories",
    "Watches",
    "Video Games",
    "Shoes & Handbags",
    "Clothing & Accessories",
    "Bags, Wallets and Luggage",
    "Jewellery",
    "Sports, Fitness & Outdoors",
    "Car & Motorbike",
    "Toys & Games",
    "Books",
    "Musical Instruments"
]

filtered_categories = {}

for name, link in unique_categories.items():

    if name in important_categories:
        filtered_categories[name] = link

filtered_categories

{'Amazon Renewed': 'https://www.amazon.in/gp/bestsellers/amazon-renewed/ref=zg_bs_nav_amazon-renewed_0',
 'Bags, Wallets and Luggage': 'https://www.amazon.in/gp/bestsellers/luggage/ref=zg_bs_nav_luggage_0',
 'Books': 'https://www.amazon.in/gp/bestsellers/books/ref=zg_bs_nav_books_0',
 'Car & Motorbike': 'https://www.amazon.in/gp/bestsellers/automotive/ref=zg_bs_nav_automotive_0',
 'Clothing & Accessories': 'https://www.amazon.in/gp/bestsellers/apparel/ref=zg_bs_nav_apparel_0',
 'Computers & Accessories': 'https://www.amazon.in/gp/bestsellers/computers/ref=zg_bs_nav_computers_0',
 'Electronics': 'https://www.amazon.in/gp/bestsellers/electronics/ref=zg_bs_nav_electronics_0',
 'Jewellery': 'https://www.amazon.in/gp/bestsellers/jewelry/ref=zg_bs_nav_jewelry_0',
 'Musical Instruments': 'https://www.amazon.in/gp/bestsellers/musical-instruments/ref=zg_bs_nav_musical-instruments_0',
 'Shoes & Handbags': 'https://www.amazon.in/gp/bestsellers/shoes/ref=zg_bs_nav_shoes_0',
 'Sports, Fitness & Outdoors': 'https://www.amazon.in/gp/bestsellers/sports/ref=zg_bs_nav_sports_0',
 'Toys & Games': 'https://www.amazon.in/gp/bestsellers/toys/ref=zg_bs_nav_toys_0',
 'Video Games': 'https://www.amazon.in/gp/bestsellers/videogames/ref=zg_bs_nav_videogames_0',
 'Watches': 'https://www.amazon.in/gp/bestsellers/watches/ref=zg_bs_nav_watches_0'}

In [10]:
#enpty dataset to keep products
all_products = []

In [11]:
first_category_name = list(filtered_categories.keys())[0]

first_category_url = filtered_categories[first_category_name]

print(first_category_name)
print(first_category_url)

Amazon Renewed
https://www.amazon.in/gp/bestsellers/amazon-renewed/ref=zg_bs_nav_amazon-renewed_0

In [12]:
response = requests.get(first_category_url, headers=headers)

print(response.status_code)

200

In [14]:
response.text

'<!doctype html><html lang="en-in" class="a-no-js" data-19ax5a9jf="dingo"><!-- sp:feature:head-start -->\n<head><script>var aPageStart = (new Date()).getTime();</script><meta charset="utf-8"/>\n<!-- sp:end-feature:head-start -->\n<!-- sp:feature:csm:head-open-part1 -->\n\n<script type=\'text/javascript\'>var ue_t0=ue_t0||+new Date();</script>\n<!-- sp:end-feature:csm:head-open-part1 -->\n<!-- sp:feature:cs-optimization -->\n<meta http-equiv=\'x-dns-prefetch-control\' content=\'on\'>\n<link rel="preconnect" href="https://images-eu.ssl-images-amazon.com" crossorigin>\n<link rel="preconnect" href="https://m.media-amazon.com" crossorigin>\n<!-- sp:end-feature:cs-optimization -->\n<!-- sp:feature:csm:head-open-part2 -->\n<script type=\'text/javascript\'>\nwindow.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;\nif (window.ue_ihb === 1) {\n\nvar ue_csm = window,\n    ue_hob = +new Date();\n(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);\n\n\n    var ue_err_chan = \'jserr\';\n(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,\npec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);\n\n\nvar ue_id = \'Q09R6MSYJG1V47NDRS5J\',\n    ue_url = \'/rd/uedata\',\n    ue_drfp = true,\n    ue_navtiming = 1,\n    ue_mid = \'A21TJRUUN4KGV\',\n    ue_sid = \'523-1181587-4892601\',\n    ue_sn = \'www.amazon.in\',\n    ue_furl = \'fls-eu.amazon.in\',\n    ue_surl = \'https://unagi.amazon.in/1/events/com.amazon.csm.nexusclient.prod\',\n    ue_int = 0,\n    ue_fcsn = 1,\n    ue_urt = 3,\n    ue_rpl_ns = \'cel-rpl\',\n    ue_ddq = 1,\n    ue_fpf = \'//fls-eu.amazon.in/1/batch/1/OP/A21TJRUUN4KGV:523-1181587-4892601:Q09R6MSYJG1V47NDRS5J$uedata=s:\',\n    ue_sbuimp = 1,\n    ue_ibft = 0,\n    ue_lpsi = 6000,\n    ue_lob = \'1\',\n    ue_act = \'-1\',\n    ue_dsbl_cel = 1,\n\n    ue_swi = 1;\nvar ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=\nv[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;\n\n(function(d,h,P){function G(a){return a&&a.replace&&a.replace(/^\\s+|\\s+$/g,"")}function v(a){return"undefined"===typeof a}function K(a){return"function"===typeof a}function E(a,b){for(var c in b)b[w](c)&&(a[c]=b[c])}function L(a){try{var b=P.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function Q(l,b,c){var t=(B||{}).type;if("device"!==c||2!==t&&1!==t){if(l){d.ue_id=a.id=a.rid=l;if("device"===c||"pre-fetch"===c)a.oid=G(l);p&&(p=p.replace(/((.*?:){2})(\\w+)/,function(a,\nb){return b+l}));H&&(e("id",H,l),H=0)}b&&(p&&(p=p.replace(/(.*?:)(\\w|-)+/,function(a,c){return c+b})),d.ue_sid=b);c&&a.tag("page-source:"+c);d.ue_fpf=p}}function R(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[w](c)&&b.push(c);return b}}function D(d,b,c,t){t=t||+new I;var f,h;if(b||v(c)){if(d)for(h in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=t,c)c[w](h)&&e(h,b,c[h]);return t}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(S=1);return e[d]=c||e[d]}function T(d,\nb,c,e,f){c="on"+c;var h=b[c];K(h)?d&&(a.h[d]=h):h=function(){};b[c]=function(a){f?(e(a),h(a)):(h(a),e(a))};b[c]&&(b[c].isUeh=1)}function U(l,b,c,t){function r(b,c){var d=[b],g=0,f={},t,k;u.latency={};c?(d.push("m=1"),f[c]=1):f=a.sc;for(k in f)if(f[w](k)){var m=e("wb",k),r=e("t",k)||{},C=e("t0",k)||a.t0,q,n;if(c||2==m){q=m?g++:"";d.push("sc"+q+"="+k);var s=z,p=z;2==m&&h.csa?(p=(s=h.csa("Content",{element:{type:"scope",slotId:k}}))&&K(s))&&+C&&s("mark","t0",+C):s=p=z;for(n in r)v(r[n])||null===r[n]||\n(d.push(n+q+"="+(r[n]-C)),p&&s("mark",V[n]||n,+r[n]));d.push("t"+q+"="+r[l]);u.latency["t"+q]=r[l];if(e("ctb",k)||e("wb",k))t=1}}!A&&t&&d.push("ctb=1");return d.join("&")}function C(b,c,g,e,l){if(b){var f=d.ue_err;d.ue_url&&!d.ue_drfp&&!e&&!l&&b&&0<b.length&&(e=new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));p?(l=h.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+l(b)+":"+(+new I-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&\nf.startTimer();a.b&&(f=a.b,a.b="",C(f,c,g,1))}}function q(b){var c=B?B.type:z,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!S||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),v(a.isNRBF)&&(d=a.ssw(a.oid),d.e||v(d.val)||(a.isNRBF=1<d.val?0:1)),v(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+a.isBFT);return b}if(!a.paused&&(b||v(c))){for(var m in c)c[w](m)&&e(m,b,c[m]);a.isBFonMshop||D("pc",b,\nc);m="ld"===l&&b&&e("wb",b);var n=e("id",b)||a.id;m||n===a.oid||(H=b,ea(n,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),e("pty",b),e("spty",b)));var n=e("id",b)||a.id,s=e("id2",b)||d.ue_id2,g=a.url+"?"+l+"&v="+a.v+"&id="+n,A=e("ctb",b)||e("wb",b),u={eventName:l,version:a.v,id:n,sessionId:d.ue_sid||"",obfuscatedMarketplaceId:d.ue_mid||""},x;A&&(g+="&ctb="+A);s&&(g+="&id2="+s);1<d.ueinit&&(g+="&ic="+d.ueinit);if(!("ld"!=l&&"ul"!=l||b&&b!=n)){if("ld"==l){try{h[M]&&h[M].isUeh&&(h[M]=null)}catch(L){}if(h.chrome)for(s=\n0;s<N.length;s++)W(J,N[s]);(s=P.ue_backdetect)&&s.ue_back&&s.ue_back.value++;d._uess&&(x=d._uess());a.isl=1}a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",n,"1"),a.isBFonMshop||D("tc",z,z,O));!F||a.isBFonMshop||X||(f&&E(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,\n_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:(K(F.now)&&!v(O)?new I(O+F.now())-new I:0)+a.t0}),B&&E(a.t,{ty:B.type+a.t0,rc:B.redirectCount+a.t0}),X=1);a.isBFonMshop||E(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1",u.ifr=!0)}D(l,b,c,t);var y,k;m||b&&b!==n||fa(b);(c=d.ue_mbl)&&c.cnt&&!m&&(g+=c.cnt());m?e("wb",b,2):"ld"==l&&(a.lid=G(n));for(y in a.sc)if(1==e("wb",\ny))break;if(m){if(a.s)return;g=r(g,null)}else c=r(g,null),c!=g&&(c=q(c),a.b=c),x&&(g+=x),g=r(g,b||a.id);g=q(g);if(a.b||m)for(y in a.sc)2==e("wb",y)&&delete a.sc[y];y=0;a._rt&&(g+="&rt="+a._rt());x=h.csa;if(!m&&x)for(k in c=e("t",b)||{},t=x("PageTiming"),c)c[w](k)&&t("mark",V[k]||k,c[k]);m||(a.s=0,(k=d.ue_err)&&0<k.ec&&k.pec<k.ec&&(k.pec=k.ec,g+="&ec="+k.ec+"&ecf="+k.ecf),y=e("ctb",b),"ld"!==l||b||a.markers?a.markers&&a.isl&&!m&&b&&E(a.markers,e("t",b)):(a.markers={},E(a.markers,e("t",b))),e("t",b,\n{}));a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),u.csmtags=a.tag(),a.tag=R());k=a.viz||[];if(c=k.length)k=k.splice(0,c),g+="&viz="+k.join("|"),u.viz=k;v(d.ue_pty)||(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti,u.pty=d.ue_pty,u.spty=d.ue_spty,u.pti=d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!a._ui||b&&b!=n||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;C(g,l,y,m,b&&"string"===typeof b&&-1!==b.indexOf("csa:"));m||(u.lob=d.ue_lob||"0",u.browserData=g,(b=x&&\nx("UEData"))&&b("log",u))}}function fa(a){var b=h.ue_csm_markers||{},c;for(c in b)b[w](c)&&D(c,a,z,b[c])}function A(a,b,c){c=c||h;if(c[Y])c[Y](a,b,!1);else if(c[Z])c[Z]("on"+a,b)}function W(a,b,c){c=c||h;if(c[$])c[$](a,b,!1);else if(c[aa])c[aa]("on"+a,b)}function ba(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,U(a))}}var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};h.chrome?(A(J,a),N.push(a)):e[J]=d.onUl;for(f in e)e[w](f)&&T(0,h,f,e[f]);d.ue_viz&&\nue_viz();A("load",d.onLd);D("ue")}function ea(e,b,c,f,r){var p=d.ue_mbl,q=h.csa,m=q&&q("SPA"),q=q&&q("PageTiming");p&&p.ajax&&p.ajax(b,c);m&&q&&(e={requestId:e,transitionType:"soft"},"string"===typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof r&&(e.subPageType=r,d.ue_spty=r),m("newPage",e),q("mark","transitionStart",b));a.tag("ajax-transition")}d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=h.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc=\n{};a.iel=[];a.ielf=[];a.viz=[];a.v="0.345463.0";a.paused=!1;var w="hasOwnProperty",J="beforeunload",M="on"+J,Y="addEventListener",$="removeEventListener",Z="attachEvent",aa="detachEvent",V={cf:"criticalFeature",af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},I=h.Date,F=h.performance||h.webkitPerformance,f=(F||{}).timing,B=(F||{}).navigation,O=(f||{}).navigationStart,p=d.ue_fpf,S=0,X=0,N=[],H=0,z;a.oid=G(a.id);a.lid=G(a.id);a._t0=\na.t0;a.tag=R();a.ifr=h.top!==h.self||h.frameElement?1:0;a.markers=null;a.attach=A;a.detach=W;if("000-0000000-8675309"===d.ue_sid){var ca=L("cdn-rid"),da=L("session-id");ca&&da&&Q(ca,da,"cdn")}d.uei=ba;d.ueh=T;d.ues=e;d.uet=D;d.uex=U;a.reset=Q;a.pause=function(d){a.paused=d};ba()})(ue_csm,ue_csm.window,ue_csm.document);\n\n\nue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");\n\nue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");\n(function(b){var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);\n\n\n\nvar ue_hoe = +new Date();\n}\nwindow.ueinit = window.ue_ihb;\n</script>\n\n<!-- 12a1am3vtaub6yjbtd64s0 -->\n<script>window.ue && ue.count && ue.count(\'CSMLibrarySize\', 10514)</script>\n<!-- sp:end-feature:csm:head-open-part2 -->\n<!-- sp:feature:aui-assets -->\n<link rel="stylesheet" href="https://m.media-amazon.com/images/I/21m27k0y9EL._RC|51O4AcYxQyL.css_.css?AUIClients/AmazonUI" />\n<link rel="stylesheet" href="https://m.media-amazon.com/images/I/11WsGYSItxL._RC|01DE6WSvLKL.css,41ixaNR85ML.css,3182OVlP7IL.css,21JMC7OC91L.css,01xH+fhFIJL.css,0168Xo81wHL.css,413Vvv3GONL.css,1170nDgl0uL.css,01Rw4F+QU6L.css,11NeGmEx+fL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01eVBHHaY+L.css,21D3IemrALL.css,11pDJV08stL.css,51yqRfvysvL.css,01HWrzt-WgL.css,01XPHJk60-L.css,11aX6hlPzjL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21gEzBqpmtL.css,11CFYS0t4PL.css,21TxBPhrLyL.css,01rSTIgNJIL.css,21Dt9D2TuML.css,31GD5I7tbCL.css,01i092IYHUL.css,01oaPOLX+-L.css,31Qk3MvcMIL.css,11PDZ29p-PL.css,11kbPm9N5xL.css,215WpAjwzoL.css,11sUwulETuL.css,114aTS6SjML.css,01xFKTPySiL.css,21GcfcmbahL.css,21OD8FuBraL.css,11XozyxiH7L.css,21n1oEPZnHL.css,11HVvPbE6JL.css,119Cktja74L.css,11PMguLK6gL.css,01890+Vwk8L.css,11sjvwOAToL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01VinDhK+DL.css,31un+UKeIeL.css,21msrr4h2yL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#not-trident" />\n<script>\n(function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(c,e,I,B){"use strict";c._pd=function(){var a,u;return function(C,f,h,k,b,D,v,E,F){function w(d){try{return d()}catch(J){return!1}}function l(){if(m){var d={w:c.innerWidth||b.clientWidth,h:c.innerHeight||b.clientHeight};5<Math.abs(d.w-q.w)||50<d.h-q.h?(q=d,n=4,(d=a.mobile||a.tablet?450<d.w&&d.w>d.h:1250<=d.w)?k(b,"a-ws"):b.className=v(b,"a-ws")):0<n&&(n--,x=setTimeout(l,16))}}function G(d){(m=d===B?!m:!!d)&&l()}function H(){return m}if(!u){u=!0;var r=function(){var d=["O","ms","Moz","Webkit"],\nc=e.createElement("div");return{testGradients:function(){return!0},test:function(a){var b=a.charAt(0).toUpperCase()+a.substr(1);a=(d.join(b+" ")+b+" "+a).split(" ");for(b=a.length;b--;)if(""===c.style[a[b]])return!0;return!1},testTransform3d:function(){return!0}}}(),y=b.className,z=/(^| )a-mobile( |$)/.test(y),A=/(^| )a-tablet( |$)/.test(y);a={audio:function(){return!!e.createElement("audio").canPlayType},video:function(){return!!e.createElement("video").canPlayType},canvas:function(){return!!e.createElement("canvas").getContext},\nsvg:function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in e.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!c.history||!c.history.pushState)},webworker:function(){return!!c.Worker},autofocus:function(){return"autofocus"in e.createElement("input")},\ninputPlaceholder:function(){return"placeholder"in e.createElement("input")},textareaPlaceholder:function(){return"placeholder"in e.createElement("textarea")},localStorage:function(){return"localStorage"in c&&null!==c.localStorage},orientation:function(){return"orientation"in c},touch:function(){return"ontouchend"in e},gradients:function(){return r.testGradients()},hires:function(){var a=c.devicePixelRatio&&1.5<=c.devicePixelRatio||c.matchMedia&&c.matchMedia("(min-resolution:144dpi)").matches;E("hiRes"+\n(z?"Mobile":A?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return r.testTransform3d()},touchScrolling:function(){return f(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return f(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!f(/trident|Edge/i)},android:function(){return f(/android.([1-9]|[L-Z])/i)&&!f(/trident|Edge/i)},mobile:function(){return z},\ntablet:function(){return A},rtl:function(){return"rtl"===b.dir}};for(var g in a)a.hasOwnProperty(g)&&(a[g]=w(a[g]));for(var t="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),p=0;p<t.length;p++)a[t[p]]=w(function(){return r.test(t[p])});var m=!0,x=0,q={w:0,h:0},n=4;l();h(c,"resize",function(){clearTimeout(x);n=4;l()});b.className=v(b,"a-no-js");k(b,"a-js");!f(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||c.navigator.standalone||f(/safari/i)||k(b,"a-ember");\nh=[];for(g in a)a.hasOwnProperty(g)&&a[g]&&h.push("a-"+g.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));k(b,h.join(" "));b.setAttribute("data-aui-build-date",F);C.register("p-detect",function(){return{capabilities:a,localStorage:a.localStorage&&D,toggleResponsiveGrid:G,responsiveGridEnabled:H}});return a||{}}}}()})(window,document,Date);(function(a,p,q,k){function m(e,b,c,g){a.P.when.apply(a.P,b).register("flow:"+e,function(){var a=g.apply(this,arguments);return c||a})}function l(e){a.P.log(e,"FATAL","AmazonUIPageJS@AUIDefineJS")}function f(a,b,c){Object.defineProperty(a,b,{value:c,writable:!1})}function n(e,b,c){"string"!==typeof e&&a.P.error("Anonymous modules are not supported.");var g=c!==k?c:"function"===typeof b?b:k;g||a.P.error("A callback must be provided");var f,h=[];if(c&&Array.isArray(b)&&(h=b.reduce(function(b,d){if("module"===\nd||"require"===d)a.P.error(\'"module" or "require" injection is not supported.\');else if("exports"===d){d=f={};var c="flow:"+e+"-exports";a.P.declare(c,d);b.push(c)}else 0!==d.lastIndexOf("@amzn/",0)?l("Dependency "+d+" does not begin with \'@amzn/\'"):b.push("flow:"+d);return b},[]),b.length!==h.length))return;m(e,h,f,g)}"use strict";Object.prototype.hasOwnProperty.call(a,"aui")?l("AUIDefineJS is already present globally"):(f(a,"aui",{}),f(a.aui,"amd_define",n))})(window,document,Date);(function(g,h,C,D){function K(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function L(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function p(a,b,c,f){b=b&&c?b+a+c:b||c;return f?p(a,b,f):b}function y(a,b,c){try{Object.defineProperty(a,b,{value:c,writable:!1})}catch(f){a[b]=c}return c}function M(a,b){a.className=\nN(a,b)+" "+b}function N(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function aa(a,b,c){var f=c=a.length,e=function(){f--||(E.push(b),F||(m?m.set(z):setTimeout(z,0),F=!0))};for(e();c--;)O[a[c]]?e():(u[a[c]]=u[a[c]]||[]).push(e)}function ba(a,b,c,f,e){var d=h.createElement(a?"script":"link");x(d,"error",f);e&&x(d,"load",e);a?(d.type="text/javascript",d.async=!0,c&&/AUIClients|images[/]I/.test(b)&&d.setAttribute("crossorigin","anonymous"),d.src=b):(d.rel="stylesheet",\nd.href=b);h.getElementsByTagName("head")[0].appendChild(d)}function P(a,b){return function(c,f){function e(){ba(b,c,d,function(b){G?q("resource_unload"):d?(d=!1,q("resource_retry"),e()):(q("resource_error"),a.log("Asset failed to load: "+c));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},f)}if(Q[c])return!1;Q[c]=!0;q("resource_count");var d=!0;return!e()}}function ca(a,b,c){for(var f={name:a,guard:function(c){return b.guardFatal(a,c)},guardTime:function(a){return b.guardTime(a)},\nlogError:function(c,d,e){b.logError(c,d,e,a)}},e=[],d=0;d<c.length;d++)A.hasOwnProperty(c[d])&&(e[d]=H.hasOwnProperty(c[d])?H[c[d]](A[c[d]],f):A[c[d]]);return e}function v(a,b,c,f,e){return function(d,k){function n(){var a=null;f?a=k:"function"===typeof k&&(q.start=r(),a=k.apply(g,ca(d,h,l)),q.end=r());if(b){A[d]=a;a=d;for(O[a]=!0;(u[a]||[]).length;)u[a].shift()();delete u[a]}q.done=!0}var h=e||this;"function"===typeof d&&(k=d,d=D);b&&(d=d?d.replace(R,""):"__NONAME__",I.hasOwnProperty(d)&&h.error(p(", reregistered by ",\np(" by ",d+" already registered",I[d]),h.attribution),d),I[d]=h.attribution);for(var l=[],m=0;m<a.length;m++)l[m]=a[m].replace(R,"");var q=w[d||"anon"+ ++da]={depend:l,registered:r(),namespace:h.namespace};d&&ea.hasOwnProperty(d);c?n():aa(l,h.guardFatal(d,n),d);return{decorate:function(a){H[d]=h.guardFatal(d,a)}}}}function S(a){return function(){var b=Array.prototype.slice.call(arguments);return{execute:v(b,!1,a,!1,this),register:v(b,!0,a,!1,this)}}}function J(a,b){return function(c,f){f||(f=c,c=\nD);var e=this.attribution;return function(){n.push(b||{attribution:e,n

In [15]:
category_soup = BeautifulSoup(response.text, "lxml")

In [16]:
products = category_soup.find_all("div", attrs={"data-asin": True})

print(len(products))

30

In [17]:
first_product = products[0]

print(first_product.prettify()[:3000])

<div class="_cDEzb_iveVideoWrapper_JJ34T" data-asin="B07R2K5RNX">
 <div class="a-section zg-bdg-ctr">
  <div class="a-section zg-bdg-body zg-bdg-clr-body aok-float-left">
   <span class="zg-bdg-text">
    #1
   </span>
  </div>
  <div class="a-section zg-bdg-tri zg-bdg-clr-tri aok-float-left">
  </div>
 </div>
 <div class="zg-grid-general-faceout">
  <span>
   <div class="p13n-sc-uncoverable-faceout" id="B07R2K5RNX">
    <a aria-hidden="true" class="a-link-normal aok-block" href="/Renewed-Maono-AU-400-Lavalier-Microphone/dp/B07R2K5RNX/ref=zg_bs_g_amazon-renewed_d_sccl_1/523-1181587-4892601?psc=1" tabindex="-1">
     <div class="a-section a-spacing-mini _cDEzb_noop_3Xbw5">
      <img alt="(Renewed) Maono AU-400 Lavalier Microphone (Black)" class="a-dynamic-image p13n-sc-dynamic-image p13n-product-image" data-a-dynamic-image='{"https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL300_SR300,200_.jpg":[300,200],"https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL600_SR600,400_.jpg":[600,400],"https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL900_SR900,600_.jpg":[900,600]}' height="200px" src="https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL300_SR300,200_.jpg" style="max-width:300px;max-height:200px"/>
     </div>
    </a>
    <div>
     <div>
      <a class="a-link-normal aok-block" href="/Renewed-Maono-AU-400-Lavalier-Microphone/dp/B07R2K5RNX/ref=zg_bs_g_amazon-renewed_d_sccl_1/523-1181587-4892601?psc=1" role="link">
       <span>
        <div class="_cDEzb_p13n-sc-css-line-clamp-4_2q2cc">
         (Renewed) Maono AU-400 Lavalier Microphone (Black)
        </div>
       </span>
      </a>
      <div class="a-row">
       <div class="a-icon-row">
        <a aria-label="3.8 out of 5 stars, 1,022 ratings" class="a-link-normal" href="/product-reviews/B07R2K5RNX/ref=zg_bs_g_amazon-renewed_d_sccl_1_cr/523-1181587-4892601">
         <i aria-hidden="true" class="a-icon a-icon-star-small a-star-small-4 aok-align-top">
          <span class="a-icon-alt">
           3.8 out of 5 stars
          </span>
         </i>
         <span aria-hidden="true" class="a-size-small">
          1,022
         </span>
        </a>
       </div>
      </div>
     </div>
    </div>
   </div>
  </span>
 </div>
 <div class="watch-button-placeholder aok-hidden">
 </div>
</div>

In [18]:
title = first_product.find("img")["alt"]

print(title)

(Renewed) Maono AU-400 Lavalier Microphone (Black)

In [19]:
asin = first_product["data-asin"]

print(asin)

B07R2K5RNX

In [20]:
rank = first_product.find("span", class_="zg-bdg-text").text.strip()

print(rank)

#1

In [24]:
reviews_tag = first_product.find("span", class_="a-size-small")

print(reviews_tag)

<span aria-hidden="true" class="a-size-small">1,022</span>

In [25]:
reviews = reviews_tag.text.strip()

print(reviews)

1,022

In [26]:
name_tag = first_product.find("div", class_="_cDEzb_p13n-sc-css-line-clamp-4_2q2cc")

print(name_tag)

<div class="_cDEzb_p13n-sc-css-line-clamp-4_2q2cc">(Renewed) Maono AU-400 Lavalier Microphone (Black)</div>

In [27]:
product_name = name_tag.text.strip()

print(product_name)

(Renewed) Maono AU-400 Lavalier Microphone (Black)

In [28]:
link_tag = first_product.find("a", class_="a-link-normal aok-block")

print(link_tag)

<a aria-hidden="true" class="a-link-normal aok-block" href="/Renewed-Maono-AU-400-Lavalier-Microphone/dp/B07R2K5RNX/ref=zg_bs_g_amazon-renewed_d_sccl_1/523-1181587-4892601?psc=1" tabindex="-1"><div class="a-section a-spacing-mini _cDEzb_noop_3Xbw5"><img alt="(Renewed) Maono AU-400 Lavalier Microphone (Black)" class="a-dynamic-image p13n-sc-dynamic-image p13n-product-image" data-a-dynamic-image='{"https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL300_SR300,200_.jpg":[300,200],"https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL600_SR600,400_.jpg":[600,400],"https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL900_SR900,600_.jpg":[900,600]}' height="200px" src="https://images-eu.ssl-images-amazon.com/images/I/61qQrv9iAfL._AC_UL300_SR300,200_.jpg" style="max-width:300px;max-height:200px"/></div></a>

In [29]:
product_link = "https://www.amazon.in" + link_tag["href"]

print(product_link)

https://www.amazon.in/Renewed-Maono-AU-400-Lavalier-Microphone/dp/B07R2K5RNX/ref=zg_bs_g_amazon-renewed_d_sccl_1/523-1181587-4892601?psc=1

In [30]:
asin = first_product["data-asin"]

print(asin)

B07R2K5RNX

In [31]:
price_tag = first_product.find("span", class_="_cDEzb_p13n-sc-price_3mJ9Z")

print(price_tag)

None

In [32]:
if price_tag:
    price = price_tag.text.strip()
else:
    price = "Not Available"

print(price)

Not Available

In [33]:
all_spans = first_product.find_all("span")

for span in all_spans:
    print(span.text)

#1
(Renewed) Maono AU-400 Lavalier Microphone (Black)3.8 out of 5 stars 1,022
(Renewed) Maono AU-400 Lavalier Microphone (Black)
3.8 out of 5 stars
1,022

In [34]:
important_categories.remove("Amazon Renewed")

In [35]:
print(important_categories)

['Mobiles', 'Electronics', 'Computers & Accessories', 'Watches', 'Video Games', 'Shoes & Handbags', 'Clothing & Accessories', 'Bags, Wallets and Luggage', 'Jewellery', 'Sports, Fitness & Outdoors', 'Car & Motorbike', 'Toys & Games', 'Books', 'Musical Instruments']

In [36]:
electronics_url = filtered_categories["Electronics"]

print(electronics_url)

https://www.amazon.in/gp/bestsellers/electronics/ref=zg_bs_nav_electronics_0

In [40]:
response = requests.get(electronics_url, headers=headers)

print(response.status_code)

200

In [41]:
electronics_soup = BeautifulSoup(response.text, "lxml")

In [43]:
products = electronics_soup.find_all(
    "div",
    attrs={"data-asin":True}
)
print(len(products))

30

In [44]:
first_product = products[0]
print(first_product.prettify()[:3000])

<div class="_cDEzb_iveVideoWrapper_JJ34T" data-asin="B0GVYDLJJQ">
 <div class="a-section zg-bdg-ctr">
  <div class="a-section zg-bdg-body zg-bdg-clr-body aok-float-left">
   <span class="zg-bdg-text">
    #1
   </span>
  </div>
  <div class="a-section zg-bdg-tri zg-bdg-clr-tri aok-float-left">
  </div>
 </div>
 <div class="zg-grid-general-faceout">
  <span>
   <div class="p13n-sc-uncoverable-faceout" id="B0GVYDLJJQ">
    <a aria-hidden="true" class="a-link-normal aok-block" href="/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYDLJJQ/ref=zg_bs_g_electronics_d_sccl_1/523-0251976-7207436?psc=1" tabindex="-1">
     <div class="a-section a-spacing-mini _cDEzb_noop_3Xbw5">
      <img alt="OnePlus Nord CE6 Lite | 6GB+128GB | Hyper Black | Segment's Fastest Dimensity 7400 Apex Processor | 7000mAh Battery | Segment" class="a-dynamic-image p13n-sc-dynamic-image p13n-product-image" data-a-dynamic-image='{"https://images-eu.ssl-images-amazon.com/images/I/61T18EfkX0L._AC_UL300_SR300,200_.jpg":[300,200],"https://images-eu.ssl-images-amazon.com/images/I/61T18EfkX0L._AC_UL600_SR600,400_.jpg":[600,400],"https://images-eu.ssl-images-amazon.com/images/I/61T18EfkX0L._AC_UL900_SR900,600_.jpg":[900,600]}' height="200px" src="https://images-eu.ssl-images-amazon.com/images/I/61T18EfkX0L._AC_UL300_SR300,200_.jpg" style="max-width:300px;max-height:200px"/>
     </div>
    </a>
    <div>
     <div>
      <a class="a-link-normal aok-block" href="/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYDLJJQ/ref=zg_bs_g_electronics_d_sccl_1/523-0251976-7207436?psc=1" role="link">
       <span>
        <div class="_cDEzb_p13n-sc-css-line-clamp-5_2l-dX">
         OnePlus Nord CE6 Lite | 6GB+128GB | Hyper Black | Segment's Fastest Dimensity 7400 Apex Processor | 7000mAh Battery | Segment's Highest 144Hz Refresh Rate | 50MP Main Camera, 4K Video Recording
        </div>
       </span>
      </a>
     </div>
    </div>
   </div>
  </span>
 </div>
 <div class="watch-button-placeholder aok-hidden">
 </div>
</div>

In [45]:
price_tag = first_product.find("span")

print(price_tag)

<span class="zg-bdg-text">#1</span>

In [47]:
all_spans = first_product.find_all("span")

for span in all_spans:
    text = span.text.strip()
    
    if "₹" in text:
        print(text)

In [49]:
third_product = products[1]

print(third_product.text)

#2OnePlus Nord CE6 | 8GB+256GB | Pitch Black | Snapdragon 7s Gen 4 | Segment's Fastest Touch Response | 8000mAh Battery | 144Hz 1.5K AMOLED Display | 50MP Main + 32MP Selfie 4K Cameras | IP66,68,69,69K3.9 out of 5 stars 251 offer from ₹32,998.00

In [50]:
all_spans = third_product.find_all("span")

for span in all_spans:
    text = span.text.strip()
    
    if "₹" in text:
        print(span)

<span><div class="p13n-sc-uncoverable-faceout" id="B0GWLJL55D"><a aria-hidden="true" class="a-link-normal aok-block" href="/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLJL55D/ref=zg_bs_g_electronics_d_sccl_2/523-0251976-7207436?psc=1" tabindex="-1"><div class="a-section a-spacing-mini _cDEzb_noop_3Xbw5"><img alt="OnePlus Nord CE6 | 8GB+256GB | Pitch Black | Snapdragon 7s Gen 4 | Segment's Fastest Touch Response | 8000mAh Battery | 144Hz" class="a-dynamic-image p13n-sc-dynamic-image p13n-product-image" data-a-dynamic-image='{"https://images-eu.ssl-images-amazon.com/images/I/61Di24QT6GL._AC_UL300_SR300,200_.jpg":[300,200],"https://images-eu.ssl-images-amazon.com/images/I/61Di24QT6GL._AC_UL600_SR600,400_.jpg":[600,400],"https://images-eu.ssl-images-amazon.com/images/I/61Di24QT6GL._AC_UL900_SR900,600_.jpg":[900,600]}' height="200px" src="https://images-eu.ssl-images-amazon.com/images/I/61Di24QT6GL._AC_UL300_SR300,200_.jpg" style="max-width:300px;max-height:200px"/></div></a><div><div><a class="a-link-normal aok-block" href="/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLJL55D/ref=zg_bs_g_electronics_d_sccl_2/523-0251976-7207436?psc=1" role="link"><span><div class="_cDEzb_p13n-sc-css-line-clamp-3_g3dy1">OnePlus Nord CE6 | 8GB+256GB | Pitch Black | Snapdragon 7s Gen 4 | Segment's Fastest Touch Response | 8000mAh Battery | 144Hz 1.5K AMOLED Display | 50MP Main + 32MP Selfie 4K Cameras | IP66,68,69,69K</div></span></a><div class="a-row"><div class="a-icon-row"><a aria-label="3.9 out of 5 stars, 25 ratings" class="a-link-normal" href="/product-reviews/B0GWLJL55D/ref=zg_bs_g_electronics_d_sccl_2_cr/523-0251976-7207436"><i aria-hidden="true" class="a-icon a-icon-star-small a-star-small-4 aok-align-top"><span class="a-icon-alt">3.9 out of 5 stars</span></i> <span aria-hidden="true" class="a-size-small">25</span></a></div></div><div class="a-row"><a class="a-link-normal" href="/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLJL55D/ref=zg_bs_g_electronics_d_sccl_2/523-0251976-7207436?psc=1" role="link"><span class="a-color-secondary">1 offer from <span><span class="p13n-sc-price">₹32,998.00</span></span></span></a></div></div></div></div></span>
<span class="a-color-secondary">1 offer from <span><span class="p13n-sc-price">₹32,998.00</span></span></span>
<span><span class="p13n-sc-price">₹32,998.00</span></span>
<span class="p13n-sc-price">₹32,998.00</span>

In [51]:
price_tag = third_product.find("span", class_="p13n-sc-price")

print(price_tag)

<span class="p13n-sc-price">₹32,998.00</span>

In [52]:
price = price_tag.text.strip()

print(price)

₹32,998.00

In [53]:
# Rank
rank = third_product.find("span", class_="zg-bdg-text").text.strip()

# Product Name
name = third_product.find(
    "div",
    class_="_cDEzb_p13n-sc-css-line-clamp-3_g3dy1"
).text.strip()

# Reviews
reviews = third_product.find(
    "span",
    class_="a-size-small"
).text.strip()

# Price
price = third_product.find(
    "span",
    class_="p13n-sc-price"
).text.strip()

# ASIN
asin = third_product["data-asin"]

# Product Link
link = third_product.find(
    "a",
    class_="a-link-normal aok-block"
)["href"]

product_link = "https://www.amazon.in" + link

In [54]:
product_data = {
    "Rank": rank,
    "Product Name": name,
    "Reviews": reviews,
    "Price": price,
    "ASIN": asin,
    "Product Link": product_link
}

print(product_data)

{'Rank': '#2', 'Product Name': "OnePlus Nord CE6 | 8GB+256GB | Pitch Black | Snapdragon 7s Gen 4 | Segment's Fastest Touch Response | 8000mAh Battery | 144Hz 1.5K AMOLED Display | 50MP Main + 32MP Selfie 4K Cameras | IP66,68,69,69K", 'Reviews': '25', 'Price': '₹32,998.00', 'ASIN': 'B0GWLJL55D', 'Product Link': 'https://www.amazon.in/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLJL55D/ref=zg_bs_g_electronics_d_sccl_2/523-0251976-7207436?psc=1'}

In [55]:
import os

os.makedirs("raw_html", exist_ok=True)

print("Folder created")

Folder created

In [56]:
wanted_categories = [
    "Books",
    "Computers & Accessories",
    "Electronics",
    "Jewellery",
    "Clothing & Accessories",
    "Shoes & Handbags",
    "Sports, Fitness & Outdoors",
    "Toys & Games",
    "Video Games",
    "Musical Instruments",
    "Bags, Wallets and Luggage"
]

In [57]:
categories = {}

all_links = soup.find_all("a")

for link in all_links:

    category_name = link.text.strip()

    if category_name in wanted_categories:

        href = link.get("href")

        full_url = "https://www.amazon.in" + href

        categories[category_name] = full_url

print(categories)

{'Electronics': 'https://www.amazon.in/gp/bestsellers/electronics/ref=zg_bs_nav_electronics_0', 'Toys & Games': 'https://www.amazon.in/gp/bestsellers/toys/ref=zg_bs_nav_toys_0', 'Books': 'https://www.amazon.in/gp/bestsellers/books/ref=zg_bs_nav_books_0', 'Sports, Fitness & Outdoors': 'https://www.amazon.in/gp/bestsellers/sports/ref=zg_bs_nav_sports_0', 'Video Games': 'https://www.amazon.in/gp/bestsellers/videogames/ref=zg_bs_nav_videogames_0', 'Bags, Wallets and Luggage': 'https://www.amazon.in/gp/bestsellers/luggage/ref=zg_bs_nav_luggage_0', 'Clothing & Accessories': 'https://www.amazon.in/gp/bestsellers/apparel/ref=zg_bs_nav_apparel_0', 'Computers & Accessories': 'https://www.amazon.in/gp/bestsellers/computers/ref=zg_bs_nav_computers_0', 'Jewellery': 'https://www.amazon.in/gp/bestsellers/jewelry/ref=zg_bs_nav_jewelry_0', 'Musical Instruments': 'https://www.amazon.in/gp/bestsellers/musical-instruments/ref=zg_bs_nav_musical-instruments_0', 'Shoes & Handbags': 'https://www.amazon.in/gp/bestsellers/shoes/ref=zg_bs_nav_shoes_0'}

In [58]:
headers = {
    "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
}

In [59]:
#delay between requests or we will get detected adn get blocked
import time

In [60]:
for category_name, url in categories.items():

    print(f"Scraping {category_name}")

    for page in range(1, 3):

        if page == 1:
            page_url = url

        else:
            page_url = url + f"?pg={page}"

        response = requests.get(page_url, headers=headers)

        file_name = f"raw_html/{category_name}_page{page}.html"

        with open(file_name, "w", encoding="utf-8") as file:

            file.write(response.text)

        print(f"Saved: {file_name}")

        time.sleep(2)

Scraping Electronics
Saved: raw_html/Electronics_page1.html
Saved: raw_html/Electronics_page2.html
Scraping Toys & Games
Saved: raw_html/Toys & Games_page1.html
Saved: raw_html/Toys & Games_page2.html
Scraping Books
Saved: raw_html/Books_page1.html
Saved: raw_html/Books_page2.html
Scraping Sports, Fitness & Outdoors
Saved: raw_html/Sports, Fitness & Outdoors_page1.html
Saved: raw_html/Sports, Fitness & Outdoors_page2.html
Scraping Video Games
Saved: raw_html/Video Games_page1.html
Saved: raw_html/Video Games_page2.html
Scraping Bags, Wallets and Luggage
Saved: raw_html/Bags, Wallets and Luggage_page1.html
Saved: raw_html/Bags, Wallets and Luggage_page2.html
Scraping Clothing & Accessories
Saved: raw_html/Clothing & Accessories_page1.html
Saved: raw_html/Clothing & Accessories_page2.html
Scraping Computers & Accessories
Saved: raw_html/Computers & Accessories_page1.html
Saved: raw_html/Computers & Accessories_page2.html
Scraping Jewellery
Saved: raw_html/Jewellery_page1.html
Saved: raw_html/Jewellery_page2.html
Scraping Musical Instruments
Saved: raw_html/Musical Instruments_page1.html
Saved: raw_html/Musical Instruments_page2.html
Scraping Shoes & Handbags
Saved: raw_html/Shoes & Handbags_page1.html
Saved: raw_html/Shoes & Handbags_page2.html

In [62]:
html_files = os.listdir("raw_html")

print(len(html_files))
print(html_files)

23
['.ipynb_checkpoints', 'Bags, Wallets and Luggage_page1.html', 'Bags, Wallets and Luggage_page2.html', 'Books_page1.html', 'Books_page2.html', 'Clothing & Accessories_page1.html', 'Clothing & Accessories_page2.html', 'Computers & Accessories_page1.html', 'Computers & Accessories_page2.html', 'Electronics_page1.html', 'Electronics_page2.html', 'Jewellery_page1.html', 'Jewellery_page2.html', 'Musical Instruments_page1.html', 'Musical Instruments_page2.html', 'Shoes & Handbags_page1.html', 'Shoes & Handbags_page2.html', 'Sports, Fitness & Outdoors_page1.html', 'Sports, Fitness & Outdoors_page2.html', 'Toys & Games_page1.html', 'Toys & Games_page2.html', 'Video Games_page1.html', 'Video Games_page2.html']

In [64]:
all_products = []

In [66]:
for file_name in html_files:

    if not file_name.endswith(".html"):
        continue

    file_path = os.path.join("raw_html", file_name)

    with open(file_path, "r", encoding="utf-8") as file:

        html_content = file.read()

    soup = BeautifulSoup(html_content, "lxml")

    print(file_name)

Bags, Wallets and Luggage_page1.html
Bags, Wallets and Luggage_page2.html
Books_page1.html
Books_page2.html
Clothing & Accessories_page1.html
Clothing & Accessories_page2.html
Computers & Accessories_page1.html
Computers & Accessories_page2.html
Electronics_page1.html
Electronics_page2.html
Jewellery_page1.html
Jewellery_page2.html
Musical Instruments_page1.html
Musical Instruments_page2.html
Shoes & Handbags_page1.html
Shoes & Handbags_page2.html
Sports, Fitness & Outdoors_page1.html
Sports, Fitness & Outdoors_page2.html
Toys & Games_page1.html
Toys & Games_page2.html
Video Games_page1.html
Video Games_page2.html

In [70]:
for file_name in html_files:

    if not file_name.endswith(".html"):
        continue

    file_path = os.path.join("raw_html", file_name)

    with open(file_path, "r", encoding="utf-8") as file:

        html_content = file.read()

    soup = BeautifulSoup(html_content, "lxml")

    print(file_name)

    products = soup.find_all(
        "div",
        attrs={"data-asin": True}
    )

    print(len(products))

Bags, Wallets and Luggage_page1.html
30
Bags, Wallets and Luggage_page2.html
30
Books_page1.html
30
Books_page2.html
30
Clothing & Accessories_page1.html
30
Clothing & Accessories_page2.html
30
Computers & Accessories_page1.html
30
Computers & Accessories_page2.html
30
Electronics_page1.html
30
Electronics_page2.html
30
Jewellery_page1.html
30
Jewellery_page2.html
30
Musical Instruments_page1.html
30
Musical Instruments_page2.html
30
Shoes & Handbags_page1.html
30
Shoes & Handbags_page2.html
30
Sports, Fitness & Outdoors_page1.html
30
Sports, Fitness & Outdoors_page2.html
30
Toys & Games_page1.html
30
Toys & Games_page2.html
30
Video Games_page1.html
30
Video Games_page2.html
30

In [71]:
all_products = []

for file_name in html_files:

    if not file_name.endswith(".html"):
        continue

    file_path = os.path.join("raw_html", file_name)

    with open(file_path, "r", encoding="utf-8") as file:

        html_content = file.read()

    soup = BeautifulSoup(html_content, "lxml")

    print(file_name)

    products = soup.find_all(
        "div",
        attrs={"data-asin": True}
    )

    print(len(products))

    for product in products:

        print(product.get("data-asin"))

Bags, Wallets and Luggage_page1.html
30
B07X6GNBNT
B097GR45SS
B0F67J5S83
B082F88NKP
B097BFM8VW
B0BL11Q9D3
B0CX8ZTM7H
B0FPDLT1CC
B0D8BG7S4P
B07CJCGM1M
B0BK1457X3
B0DJ8R2XDN
B0F5HLYQK3
B07PK41FL4
B079TN3GCD
B098FFTDKT
B09B267161
B07Q822CWX
B07YDGQQN5
B0C4FKHHVW
B0C5MKVBN9
B0FMF1CTQ2
B07M9BRCQ5
B0F5HKFPWR
B0FCYHSSKQ
B08P5ML6GK
B0FC6RZNDC
B07MWD4D4W
B0C1K5S9X4
B0GNSQ9RGN
Bags, Wallets and Luggage_page2.html
30
B09RY4WHMR
B0FSSMVXZ4
B0G6CWL9HH
B08F9SFYXQ
B0FNDBNFDB
B097JMZGP7
B0GWKCD1HN
B09T9XDQ99
B0F9FTG9ZS
B097RJ22Q3
B0CWSB5B17
B0FFTLRBX2
B0F29G1GXK
B0C7BM18PB
B0C8ZNNCQW
B0C692D6CS
B085LFPKQB
B0CF9DF3QB
B0GVSH9MJD
B083C76NYD
B0GPN9RZ6H
B0C4FKRWV8
B0F3XFTCPL
B0BW3QZBQH
B0FJ672BBN
B0F8B8Z1RL
B09B29F66W
B0CY56R6V5
B0CJ9S6HJ6
B0DX1MF3Q4
Books_page1.html
30
9357295674
9357298738
B0H1HRYJWY
9357294198
935886592X
9387779262
B0GZHQ18T4
9377396115
9390166268
1847941834
9364447670
178633089X
8172345666
9375162206
9360347981
0241252083
9551753437
9389931843
935440460X
9373949586
1760630721
9373941402
8195645755
B09LV1KHKV
B0H1M7MVXW
B0CJDVNY3L
9388144252
9357290486
8199871032
9358565810
Books_page2.html
30
9373945904
937359219X
9373171984
937516960X
9375169537
B0FNN8WSZ6
9386538601
9390183006
8194899133
8172345135
9368971331
B0H1XCW64F
8131958248
935543135X
9355434146
8183286011
8119099397
B0FRFMCFB3
9357292934
9364375157
933440857X
1786583232
9369579885
9354405118
9368020388
9354409768
9391129811
8195645798
9389178118
935369969X
Clothing & Accessories_page1.html
30
B0FRFXX2C3
B06Y2FG6R7
B010FMJKFS
B0FVSG25HR
B07MZM26XG
B0CKBXTPL1
B07JVPXV2Q
B07HJJTHD1
B0DGX12XXV
B0DNBH4W1C
B0GPQC7NXZ
B0DRFPPCRS
B0FNWQ2D1F
B09XMV6125
B09J171VHQ
B0FTX3WDH8
B0FLK6Q7NV
B0G524MFS3
B0FVY7GNBN
B0DF794BDK
B0CJFQWSYZ
B014213DS8
B071KKRY5N
B0F8ZLGG8V
B0FM4JKGSW
B0FRY6CQJM
B012SX56OG
B073WCC5YL
B0F3JHWP6T
B010FMOONG
Clothing & Accessories_page2.html
30
B0CNKMYHN8
B0DP7M6DRY
B0D4HZ615R
B0C3DH4XPJ
B0BDG16KVN
B0FNX2BNYH
B07JVPXVQG
B073X4KMH6
B0G3QD7W9B
B09CNQV8VF
B0GG459CD4
B0B5GXTK4W
B0GGHP8SR5
B010FPALNK
B09RWL4VQK
B0CBX5119W
B0DC564YDC
B08V56NV1B
B0C3HRWRBF
B0CVXRBTLC
B0FXRTBV8T
B0FNR99LWS
B07X63HHPH
B0D83WSP8C
B0DPL2XMTH
B0DSW19ZZ1
B0G4DFZLQK
B0GZ7YPP71
B0G7189R4V
B0DB5GZYHP
Computers & Accessories_page1.html
30
B098NS6PVG
B097JJ2CK6
B0DK7B3B2G
B0FHWWDRRM
B08LHTJTBB
B0CQRNWJM2
B09VTDMRY7
B09BFV96TS
B008FWZGSG
B0BTD4S4XF
B0DZ7C519W
B01DGVKBC6
B0FGVQBNSB
B01HJI0FS2
B0DFCGB2D6
B0DNFSSF3F
B08VRGH6NM
B09QGZFBPM
B0DXQFRQZP
B0BL6S8KHM
B08DDRGWTJ
B005FYNT3G
B0FJ2LY2JN
B0FMRLJ9LF
B0CR6JQT6F
B0F73SVVZH
B0CP9NSXYJ
B0FQCN6WG9
B0FJG2TL3C
B0C376RWQP
Computers & Accessories_page2.html
30
B00A0VCJPI
B0FF4XBM5N
B0DZ6T16SD
B0B296NTFV
B0D7TGDMVQ
B0D3TX2SDB
B0BBQK41CV
B0BG62HMDJ
B0GZVBHQC7
B08PFSZ7FH
B094QZLJQ6
B0DV5C5FR2
B0CHBHYLLR
B077T3BG5L
B0DXV31MLB
B0D8KQK2CY
B0BKPMD1BN
B0GP83XVS5
B08ZJG6TVT
B0D18192T2
B08CYNJ5KY
B08CF3D7QR
B0B9LDCX89
B0C2KRGMHC
B0DG5DL8TM
B07BZ5VC4H
B0F2FYKDS4
B0CP2K2XN8
B07JPX9CR7
B093QCY6YJ
Electronics_page1.html
30
B0GVYDLJJQ
B0GWLJL55D
B0GS5Y7QBF
B0FMDL81GS
B098NS6PVG
B0GRBBPBGQ
B0DCZ3WDTB
B0FN7RN9TH
B0FBRGKXHG
B0DDHM6D3L
B0D2R2MXXJ
B0D7HZ3KK9
B0F7Y54PJX
B0FM38916Y
B0D9S87H53
B0FVFJHZBP
B08TV2P1N8
B097JJ2CK6
B0FT396JRW
B0DNPWJLQC
B0DCNWN8NZ
B071Z8M4KX
B0F43VZ4H1
B0BJ72WZQ7
B0GCFKLMV1
B09GP6FBZT
B0DH3J6LB9
B0C3ZYFZ77
B0FC2YFSN4
B0000C73CQ
Electronics_page2.html
30
B0D96HMLYX
B0GL1JFK48
B0FHB5V36G
B09BFV96TS
B0FM6B9Z45
B008FWZGSG
B0BTD4S4XF
B0GQTSHLLR
B0CR7N9MD9
B0D9629NJQ
B09ZPL5VYM
B0DSC4YJRD
B0FN7QTRPY
B0D78XSMSM
B0F1D9Q5G4
B0D59RWXHH
B0FJFRYXFK
B0DBGP48NW
B0FVG14W46
B0DN1RPL19
B0DZ7C519W
B0D7MNX9Y5
B0F8BVSK21
B0GTRXVQ8N
B08JQ6CVJ3
B0FDGVNSLH
B01DGVKBC6
B0B6BLTGTT
B0FGVQBNSB
B0DJBZJM15
Jewellery_page1.html
30
B071CMQ6N2
B0DYVPP86H
B0D3DCP7JQ
B0FT8NVZSP
B0FF4M8YZK
B0GCJQF324
B0GSX2KQ7L
B0FQ63H7BS
B0DTTXM92H
B0CV3T1WBB
B0C5VKPPZJ
B0GQN2Z7KM
B0BWJ5MFRY
B0C1N366XM
B09TWW4XRJ
B0BTHBJT3L
B0CTQ25GDW
B0DFCKWRBM
B0CH6BF15Z
B07NPWP1Q6
B0D875PWX7
B0BJFCHR4W
B0GXLC54RG
B0GRTTKNJ7
B09J2VKJ43
B0GS33PX2Z
B0CDQ7XBG9
B08R3W2131
B0BX62B58N
B078KWDF1N
Jewellery_page2.html
30
B0CF1WVLS4
B0GSXFDPSG
B0FB46QM2X
B0F6VM8HJV
B08L13PPNS
B0GX1Z227Q
B0GN9HVJWF
B0DLTB9QRS
B0FHWT3PFS
B0FD7Z3TYM
B0D46Y6X5L
B0DQY44FCD
B0GBV3D79T
B0BY3MXKN9
B01N2WJ0OR
B0FTG7MPF4
B0GTZ2LSLL
B08JJ87XG4
B0DSCBKY8R
B0FB47SJMB
B08K9954FB
B09WDTP1V9
B083P2RQRB
B0GT3PJ86J
B0CJRB4S8M
B0BVB8D8XW
B0FCFSGNGT
B0FTS4FZ84
B0FFT2KX32
B07CWQNGD5
Musical Instruments_page1.html
30
B0DQD8HWWG
B0D772K8X8
B0FMQW9LZD
B0DH8BVS6Z
B07T35ZBHB
B0FMWXRQRR
B088KRHPG5
B017NPCSLI
B0DPT2ZP69
B08KWM1MHV
B072FH5KLJ
B0FHBRX7T7
B0GF1ZJ2N4
B0D8TJ7NW7
B0F2NBK7RN
B076B8G5D8
B0716FQ7SP
B0CWXRTBSZ
B0DH8BSWYF
B08317Y4VP
B08MVZGGW4
B073B6TQQY
B0DCJSVN1Z
B08G1NYPLF
B08K43SPQ1
B09ZV5JHVR
B0GMWDK829
B08GJT1WQX
B08KW4DRKL
B0F6D49DNK
Musical Instruments_page2.html
30
B00HVLUR18
B0DNSQ7NGL
B0773GB3KF
B01L77Z7WK
B09N75RFX1
B0002LI658
B08K3YDNDS
B0G39FYQZX
B0C2CNDKHZ
B0B8DMF47G
B07VTQ9QKC
B00BJF9W6I
B0FVYK38KY
B0DKNJXWVX
B0FCYMP4D2
B08TXKJTNG
B0CVWQVXP2
B09314VSYR
B098DJ7RZY
B08K41N3D1
B0GPWY4645
B09FPSM3LD
B08K8X7SSS
B0FQT4P1JP
B07ZG1C8YL
B0CVY4NN1K
B074RHGWW9
B0BLSJZC94
B07TX79NLC
B0GD193LST
Shoes & Handbags_page1.html
30
B0FR9LH4WQ
B0CSWN33CZ
B09D8CXJ2Q
B0G5L5KQNR
B0DZ6YG9TM
B0BYVSTYP8
B01N54ZM9W
B08NZ9PRN6
B0BLYGY7GY
B0BSLJ245T
B09RV5JVMM
B0BYTC95RD
B09SHVCTZF
B0BRL2SLLD
B0DCP4YY16
B0BXD4Z6F4
B0DRS8D2LD
B0F7HCTRTM
B0CNM27L5P
B08DXGDQF2
B09RGJCVW6
B0GSJXVNHC
B0DCK4FLF6
B075GCYS36
B0CCJTP414
B096BFVSFG
B09RPPS669
B0D2DLQMGY
B0FWKT6PFP
B07M8H2HR4
Shoes & Handbags_page2.html
30
B0CP9GGP5X
B0BM5QLJQC
B0DFH98P5P
B0DF5X4M9L
B09WYD48F1
B0BNHHCGCP
B0F147M1SL
B0DGQNLJX7
B0FSSTYCSN
B0BXD4FPD2
B0F8NZPC88
B08PSHLJGL
B09RBF4DTC
B0G2C8ZQWS
B0D6Z3XW47
B0C8VH1FK3
B0CKNJVLVJ
B0CLZRH145
B0CX58YTVX
B09W5Y2HVS
B0FCSLWT5J
B0CN5HXHHZ
B0DBD4JYKK
B0CZPJRDQN
B0D37LQZBY
B0FJ5X7CS4
B0CVH78TKZ
B0BWYW7B85
B096BGHSDB
B07QQDJ7G9
Sports, Fitness & Outdoors_page1.html
30
B09W5PSTBP
B0B6NSDR2H
B0B77X44MX
B0DCJYS6KG
B08H8KD72Q
B09YJ475JC
B0DMNQGRDW
B098JV1SNN
B000FI8ER8
B0C55FP5TX
B00T926QUI
B0D4DZ7WL2
B09WVXMG96
B0FD817WFP
B0DYFB76QF
B0BN1V4GYB
B08LZKPT32
B0CQ4FQ2T7
B0DX1H3GH4
B0BC47M9YL
B09G9W3WFL
B09ZLLQ3G2
B01IEVIVAC
B0B5LGN5YH
B08C7S9RNY
B0D6R39TXG
B076DC73XF
B0DHRP57T9
B0GP18M11K
B0FY2G5SY9
Sports, Fitness & Outdoors_page2.html
30
B0GLP63W9Y
B0CQRKP56R
B0B8VPCY1Q
B08B22WSP7
B0FHHG2YW4
B0CKYY1M62
B09TR8TMVR
B0CR416FGN
B0B8RSTZ4V
B0DX1T7MKW
B0FKB46S1P
B0DWKJHCTW
B0FCCNHPYX
B0B7599YRJ
B0DGXHHPCL
B07LGRJTY4
B0DZBYLWXW
B0BS3RG1CD
B0DSLDJ1GB
B09DYH5D4P
B0DWMQPKY8
B0D9VVQD2S
B09KH81K1W
B0F5BL4RNP
B0BKZK9JGB
B0GX6T69LR
B0DRKK4JJX
B0CKW4XKPC
B092ZXF779
B0GG4W7N66
Toys & Games_page1.html
30
B0D9YN4F81
B0B2F8XS9L
B00004TZY8
B0DHSFBRPB
B0CBNR2ML6
B0CM9MHFQP
B0DTJ7F2G4
B0DRPCR5VK
B08D8J88X3
B0CQJRQWHN
B0C77VNZ5D
B0D4DZ7WL2
B0FC692YW3
B0BHHKR9DN
B0CBV1WDM1
B07JKB2H59
B0FQCHD1DX
B0BVW64V54
B0CQRCSSZ6
B0FPCJ25SR
B0DZCJ1L63
B0DBF8S3HB
B0DDQ3HNCM
B0GSZ14C55
B0DQY9DPXR
B00ADZUNYK
B0BCGC1CFV
B0BLBW79NQ
B0BZP6PC25
B0CCDTXNLF
Toys & Games_page2.html
30
B0BJ2B85HG
B0FP2V7XVL
B09Y23QLNR
B0G2H71WQ4
B0FBJPY4C7
B0G9TT7DVK
B0F1MZB7N3
B0B86BQ574
B0BHZS13PQ
B0DGLXLS4S
B0CXVX19CH
B0G1K431XW
B0D7SMBSQY
B0D26V39PX
B0D5B81RCT
B0BQC9PMYS
B0D9K89DSS
B09GF6JBZN
B0C27SZCW3
B0BF585KKH
B084HCJ1VT
B076WQ3M5X
B0D319Z1YN
B00JJJIIE8
B0CYSS21S6
B0GGBMGF84
B0GFNDZKJB
B0BXX9S2YC
B0FR48VC1T
B00NHQFA1I
Video Games_page1.html
30
B07K6RYVHR
B0FRF4VSXC
B0BRZZCRPW
B0GHKLKC4R
B09XJ8FGVP
B07K6PVR8B
B0GJ6BDDX1
B0GHJZ9QSN
B093QF35KZ
B07K6RYVJ5
B0FHWBD9ZV
B0CHMXVCGH
B0F674X8GP
B0GQ3NF8HZ
B0DP6N7ZCF
B08GZ6QNTC
B0GN2F3JFY
B07P397J9Z
B0CWH7FCFX
B0F91N6WQK
B0G2MKGDFD
B0D4N2934T
B0F6VH981P
B0CMZWW78K
B0F3JRN2GP
B0F1KL383Z
B0FNDDJ1LV
B098439Y2G
B0GG5GYL25
B0CTMQ7SCD
Video Games_page2.html
30
B0GMGVT3Z8
B0D6RSFS64
B0D1CJYYV3
B0CL4NHFSS
B0BHHGX2M9
B0B6FJKRVN
B0G4M7L12R
B0CHWBMX8V
B0D1TV3HGB
B0G433389V
B0BBV2KB8R
B07BFGGNT9
B0DZ1XJ873
B0B4289TYT
B0DT5Y1FM9
B09KLX23D3
B09PLKQYDR
B0G6WWBQ96
B0CV4H53ZJ
B0D7367TK1
B08KJPLGLF
B0BHH2VYBW
B0D6RLY5YT
B0D8JJRCJN
B08SL6JRX6
B09N9MBVD1
B0C5WVDXGX
B0C5C9QVQX
B0FB5NRFWS
B0BMPLHLZ9

In [95]:
all_products = []

for file_name in html_files:

    # Skip non-html files
    if not file_name.endswith(".html"):
        continue

    file_path = os.path.join("raw_html", file_name)

    # Open HTML file
    with open(file_path, "r", encoding="utf-8") as file:

        html_content = file.read()

    # Create soup
    soup = BeautifulSoup(html_content, "lxml")

    # Find all products
    products = soup.find_all(
        "div",
        attrs={"data-asin": True}
    )

    print(f"\nProcessing: {file_name}")
    print(f"Products Found: {len(products)}")

    # Loop through products
    for product in products:

        try:

            # ASIN
            asin = product.get("data-asin")

            # Product Name
            name_tag = product.find(
                "div",
                class_="_cDEzb_p13n-sc-css-line-clamp-3_g3dy1"
            )

            # Backup selector
            if not name_tag:

                name_tag = product.find(
                    "div",
                    class_="_cDEzb_p13n-sc-css-line-clamp-4_2q2cc"
                )

            # Skip if no name
            if not name_tag:
                continue

            name = name_tag.text.strip()

            # Reviews
            reviews_tag = product.find(
                "span",
                class_="a-size-small"
            )

            if reviews_tag:

                reviews = reviews_tag.text.strip()

            else:

                reviews = "0"

            # Price
            price = None
            
            all_spans = product.find_all("span")
            
            for span in all_spans:
            
                text = span.text.strip()
            
                if "₹" in text:
            
                    price = text
                    break
            
            # Skip if no price
            if not price:
                continue

            # Print extracted data
            print(asin)
            print(name)
            print(reviews)
            print(price)
            print("-" * 50)

            # Store product
            product_data = {
                "ASIN": asin,
                "Product_Name": name,
                "Reviews": reviews,
                "Price": price
            }

            all_products.append(product_data)

        except Exception as e:

            print("Error:", e)

Processing: Bags, Wallets and Luggage_page1.html
Products Found: 30
B07X6GNBNT
Credit Card Bill
393,124
Credit Card Bill4.4 out of 5 stars 393,1243 offers from ₹10.00
--------------------------------------------------
B097GR45SS
Safari Pentagon Pro 8 Wheels 66cm Medium Size Trolley Bag, Hard Case Polypropylene, 360º Wheeling Check in Luggage, Suitcase for Travel, Trolley Bags for Travel, Luxury Beige
35,066
Safari Pentagon Pro 8 Wheels 66cm Medium Size Trolley Bag, Hard Case Polypropylene, 360º Wheeling Check in Luggage, Suitcase for Travel, Trolley Bags for Travel, Luxury Beige4.2 out of 5 stars 35,066₹1,999.00
--------------------------------------------------
B0F67J5S83
Safari Cabin Genius Alley 55cm Trolley Bag Hard Case Polypropylene, 4 Spinner Wheels, 360 Degree Wheeling Carry on Luggage, Travel Bag, Suitcase for Travel, Trolley Bags for Travel, Navy
6,454
Safari Cabin Genius Alley 55cm Trolley Bag Hard Case Polypropylene, 4 Spinner Wheels, 360 Degree Wheeling Carry on Luggage, Travel Bag, Suitcase for Travel, Trolley Bags for Travel, Navy4.0 out of 5 stars 6,454₹1,299.00
--------------------------------------------------
B082F88NKP
Billebon Premium Neck Pillow for Travelling Airplane Travel Pillow Comfortable Head Rest Neck Holder Pillow (Grey)
15,020
Billebon Premium Neck Pillow for Travelling Airplane Travel Pillow Comfortable Head Rest Neck Holder Pillow (Grey)4.0 out of 5 stars 15,020₹189.00
--------------------------------------------------
B0BL11Q9D3
Kamiliant American Tourister Harrier|Cabin Trolley Bag Small Size (56 cms) for Travel| Hard Case Polypropylene (PP) Suitcase|360° 4-Wheel Spinner Luggage Trolley|Combination Lock|Iron Grey
15,122
Kamiliant American Tourister Harrier|Cabin Trolley Bag Small Size (56 cms) for Travel| Hard Case Polypropylene (PP) Suitcase|360° 4-Wheel Spinner Luggage Trolley|Combination Lock|Iron Grey4.1 out of 5 stars 15,122₹1,199.00
--------------------------------------------------
B0FPDLT1CC
Trajectory Travel Neck Pillow for Travelling and Sleeping in Airplane Flight, Cab, Car, Train, Bus for Men and Women Grey (As seen on Shark Tank)
19,250
Trajectory Travel Neck Pillow for Travelling and Sleeping in Airplane Flight, Cab, Car, Train, Bus for Men and Women Grey (As seen on Shark Tank)3.9 out of 5 stars 19,250₹189.00
--------------------------------------------------
B0D8BG7S4P
Aristocrat Nova 15L Laptop Backpack for Men & Women with Bottle Pocket | Padded Shoulder Straps, Multi Compartments | Travel & College Bag | Dark Black
2,486
Aristocrat Nova 15L Laptop Backpack for Men & Women with Bottle Pocket | Padded Shoulder Straps, Multi Compartments | Travel & College Bag | Dark Black4.1 out of 5 stars 2,486₹299.00
--------------------------------------------------
B07CJCGM1M
American Tourister 32 Ltrs Black Casual Backpack (AMT FIZZ SCH BAG 02 - BLACK)
34,257
American Tourister 32 Ltrs Black Casual Backpack (AMT FIZZ SCH BAG 02 - BLACK)4.1 out of 5 stars 34,257₹899.00
--------------------------------------------------
B0BK1457X3
Boldfit Shoe Bag for Travel Bag for Man & Women Shoe Cover for Storage at Home Gym Reusable Travelling Accessories Organizer Pouch Travel Essentials Footwear Bags for Travelling Men -Pack of 6, Black
14,852
Boldfit Shoe Bag for Travel Bag for Man & Women Shoe Cover for Storage at Home Gym Reusable Travelling Accessories Organizer Pouch Travel Essentials Footwear Bags for Travelling Men -Pack of 6, Black4.4 out of 5 stars 14,852₹179.00
--------------------------------------------------
B0DJ8R2XDN
Roughhouse UV Umbrella for Sun & Rain – Auto Open/Close | Windproof | Travel-Friendly 3-Fold Design | SPF 50+ Coated | Big Canopy, Easy to Carry
582
Roughhouse UV Umbrella for Sun & Rain – Auto Open/Close | Windproof | Travel-Friendly 3-Fold Design | SPF 50+ Coated | Big Canopy, Easy to Carry4.0 out of 5 stars 582₹329.00
--------------------------------------------------
B0F5HLYQK3
American Tourister Liftoff+|Large Size Check-in Spinner Trolley Bag (79 cm) for Travel|360° 8 Wheel Travel Luggage|Hard Case Polypropylene (PP) Suitcase|Mounted TSA Lock|Seafoam Blue
2,404
American Tourister Liftoff+|Large Size Check-in Spinner Trolley Bag (79 cm) for Travel|360° 8 Wheel Travel Luggage|Hard Case Polypropylene (PP) Suitcase|Mounted TSA Lock|Seafoam Blue4.1 out of 5 stars 2,404₹3,499.00
--------------------------------------------------
B07PK41FL4
GLUN® Electronic Portable Digital LED Screen Luggage Weighing Scale, 50 kg/110 Lb For Multi-Purpose Use.
28,692
GLUN® Electronic Portable Digital LED Screen Luggage Weighing Scale, 50 kg/110 Lb For Multi-Purpose Use.4.1 out of 5 stars 28,692₹235.00
--------------------------------------------------
B079TN3GCD
WildHorn Olive Leather Men's Wallet (WH2050) (Brown)
5,351
WildHorn Olive Leather Men's Wallet (WH2050) (Brown)4.2 out of 5 stars 5,351₹499.00
--------------------------------------------------
B098FFTDKT
Gear Cross Training 9"/29L Large Water Resistant Duffle Bag | Travel Bag | Gym Bag for Men & Women (Black - Grey)
25,425
Gear Cross Training 9"/29L Large Water Resistant Duffle Bag | Travel Bag | Gym Bag for Men & Women (Black - Grey)4.2 out of 5 stars 25,425₹445.00
--------------------------------------------------
B09B267161
Safari Hitech Large Size 35 Ltrs Water Resistant Standard 4 Compartment Backpack - Black
6,052
Safari Hitech Large Size 35 Ltrs Water Resistant Standard 4 Compartment Backpack - Black4.2 out of 5 stars 6,052₹819.00
--------------------------------------------------
B07Q822CWX
GoTrippin by Destinio Weight Machine for Luggage - 50 kg capacity, Steel body, Lifetime replacement - Digital Portable Electronic Luggage Weighing Scale for home, travel, flights, bags (Silver, 50 kg)
14,853
GoTrippin by Destinio Weight Machine for Luggage - 50 kg capacity, Steel body, Lifetime replacement - Digital Portable Electronic Luggage Weighing Scale for home, travel, flights, bags (Silver, 50 kg)4.5 out of 5 stars 14,853₹610.00
--------------------------------------------------
B07YDGQQN5
Fur Jaden 55 LTR Rucksack Travel Backpack Bag for Trekking, Hiking with Shoe Compartment
14,034
Fur Jaden 55 LTR Rucksack Travel Backpack Bag for Trekking, Hiking with Shoe Compartment4.3 out of 5 stars 14,034₹795.00
--------------------------------------------------
B0C4FKHHVW
Stealodeal Brown 28 Slots Leather Debit/Credit/ATM Men & Women Card Holder
2,331
Stealodeal Brown 28 Slots Leather Debit/Credit/ATM Men & Women Card Holder4.2 out of 5 stars 2,331₹99.00
--------------------------------------------------
B0C5MKVBN9
Cockatoo Shoe Bag for Travel Bag for Men & Women, Shoe Cover for Storage at Home Gym Reusable Travelling Accessories, Organizer Pouch Footwear Bags for Travelling-Pack of 6(13 x 17.32 Inch)
4,542
Cockatoo Shoe Bag for Travel Bag for Men & Women, Shoe Cover for Storage at Home Gym Reusable Travelling Accessories, Organizer Pouch Footwear Bags for Travelling-Pack of 6(13 x 17.32 Inch)4.3 out of 5 stars 4,542₹150.00
--------------------------------------------------
B07M9BRCQ5
Fur Jaden Brown Textured Leatherette Stylish & Spacious Weekender Duffle Bag for Travel for Men and Women
12,169
Fur Jaden Brown Textured Leatherette Stylish & Spacious Weekender Duffle Bag for Travel for Men and Women4.3 out of 5 stars 12,169₹649.00
--------------------------------------------------
B0F5HKFPWR
American Tourister Ivy 2.0|Medium Size Check-in Spinner Trolley Bag (68 cm)|360° 8 Wheel Travel Luggage|Hard Case Polypropylene (PP) Suitcase|Combination Lock|Blue Frog
6,904
American Tourister Ivy 2.0|Medium Size Check-in Spinner Trolley Bag (68 cm)|360° 8 Wheel Travel Luggage|Hard Case Polypropylene (PP) Suitcase|Combination Lock|Blue Frog4.2 out of 5 stars 6,904₹2,799.00
--------------------------------------------------
B0FCYHSSKQ
Lifelong Shoe Bags for Travel, Drawstring Travel Shoe Bags for Packing, Dustproof Portable Travel Shoe Storage Bag for Men and Women, Clear, Large, 10 Pack
529
Lifelong Shoe Bags for Travel, Drawstring Travel Shoe Bags for Packing, Dustproof Portable Travel Shoe Storage Bag for Men and Women, Clear, Large, 10 Pack4.3 out of 5 stars 529₹199.00
--------------------------------------------------
B08P5ML6GK
WildHorn Wildhorn India Brown Leather Men's Wallet (WH7311BROWN)
37,916
WildHorn Wildhorn India Brown Leather Men's Wallet (WH7311BROWN)4.1 out of 5 stars 37,916₹597.00
--------------------------------------------------
B0FC6RZNDC
Aristocrat Polycarbonate Spinner Comet Cabin Trolley Bag 56cm|Small|Hard Luggage| Smooth 8-Wheel Suitcase|Combination Lock with Sturdy Zipper|Full Fabric Convipack|3-Year International Warranty(Green)
2,708
Aristocrat Polycarbonate Spinner Comet Cabin Trolley Bag 56cm|Small|Hard Luggage| Smooth 8-Wheel Suitcase|Combination Lock with Sturdy Zipper|Full Fabric Convipack|3-Year International Warranty(Green)4.1 out of 5 stars 2,708₹1,409.00
--------------------------------------------------
B07MWD4D4W
M MEDLER Epoch Nylon 55 litres Waterproof Strolley Duffle Bag- 2 Wheels - Luggage Bag - (Navy Blue)
32,879
M MEDLER Epoch Nylon 55 litres Waterproof Strolley Duffle Bag- 2 Wheels - Luggage Bag - (Navy Blue)3.5 out of 5 stars 32,879₹599.00
--------------------------------------------------
B0C1K5S9X4
Aristocrat Medium Commander 69Cms Premium Polyester with PVC Coating Soft Sided Check-in 4 Spinner Wheels Black Suitcase
1,974
Aristocrat Medium Commander 69Cms Premium Polyester with PVC Coating Soft Sided Check-in 4 Spinner Wheels Black Suitcase4.3 out of 5 stars 1,974₹2,109.00
--------------------------------------------------
B0GNSQ9RGN
Robustt Capsule Mini Foldable Travel Umbrella | UPF 50+ UV & Rain Protection | 3 Fold Compact | for Women, Men & Kids | Windproof, Waterproof, Pocket-Size with Storage Case
39
Robustt Capsule Mini Foldable Travel Umbrella | UPF 50+ UV & Rain Protection | 3 Fold Compact | for Women, Men & Kids | Windproof, Waterproof, Pocket-Size with Storage Case4.7 out of 5 stars 39₹499.00
--------------------------------------------------

Processing: Bags, Wallets and Luggage_page2.html
Products Found: 30
B09RY4WHMR
Wooum Polyester Toiletry Bag for Men & Women, Travel Pouch for Toiletries Shaving Kit & Cosmetics, Water Resistance Pouch for Travel Accessories, Organizer Travel Pouch for Make Up, Black
3,219
Wooum Polyester Toiletry Bag for Men & Women, Travel Pouch for Toiletries Shaving Kit & Cosmetics, Water Resistance Pouch for Travel Accessories, Organizer Travel Pouch for Make Up, Black4.4 out of 5 stars 3,219₹269.00
--------------------------------------------------
B0FSSMVXZ4
TrollGadgets® Guardian Bell Keychain for Bike & Car | Tibetan Texture Bell Keychain with Evil Eye & Silver Hook | Good Luck Charm
649
TrollGadgets® Guardian Bell Keychain for Bike & Car | Tibetan Texture Bell Keychain with Evil Eye & Silver Hook | Good Luck Charm4.4 out of 5 stars 649₹189.00
--------------------------------------------------
B0G6CWL9HH
Catron Waterproof Makeup Pouch Bag for Women Travel Kit Washbag Pink Faux Leather, Traveling Cosmetics, Brushes & Accessories Box Toiletry Organiser with Clear Window, Set of 3 (Pink)
129
Catron Waterproof Makeup Pouch Bag for Women Travel Kit Washbag Pink Faux Leather, Traveling Cosmetics, Brushes & Accessories Box Toiletry Organiser with Clear Window, Set of 3 (Pink)4.4 out of 5 stars 129₹199.00
--------------------------------------------------
B08F9SFYXQ
BEAUTY GIRLS BY HOTSHOT |SCHOOL BAG|TUTION BAG|COLLEGE BACKPACK|FOR GIRLS & WOMEN|18.5 INCH|32 L WATER RESISTANT |SCHOOL BAG FOR GIRLS
3,898
BEAUTY GIRLS BY HOTSHOT |SCHOOL BAG|TUTION BAG|COLLEGE BACKPACK|FOR GIRLS & WOMEN|18.5 INCH|32 L WATER RESISTANT |SCHOOL BAG FOR GIRLS4.3 out of 5 stars 3,898₹799.00
--------------------------------------------------
B0FNDBNFDB
Safari Genius Theo 8 Wheels 55cm Cabin Size Trolley Bag, Hard Case Polycarbonate, 360 Degree Wheeling Small Carry-on Luggage, Suitcase for Travel, Trolley Bags for Travel, Sage Green
1,143
Safari Genius Theo 8 Wheels 55cm Cabin Size Trolley Bag, Hard Case Polycarbonate, 360 Degree Wheeling Small Carry-on Luggage, Suitcase for Travel, Trolley Bags for Travel, Sage Green4.1 out of 5 stars 1,143₹1,399.00
--------------------------------------------------
B097JMZGP7
Safari Medium Crescent 8 Wheels 66cm Check-in Trolley Bag Hard Case Polycarbonate 360 Degree Wheeling System Luggage, Travel Bag, Suitcase for Travel, Trolley Bags for Travel, Ink Blue
2,975
Safari Medium Crescent 8 Wheels 66cm Check-in Trolley Bag Hard Case Polycarbonate 360 Degree Wheeling System Luggage, Travel Bag, Suitcase for Travel, Trolley Bags for Travel, Ink Blue4.2 out of 5 stars 2,975₹2,099.00
--------------------------------------------------
B0GWKCD1HN
OTTAVO Premium Guardian Bell Keychain for Bike & Car | Tibetan Texture Bell Keychain with Evil Eye & Silver Hook | Good Luck Charm with Laser-Engraved Wooden Gift Box
20
OTTAVO Premium Guardian Bell Keychain for Bike & Car | Tibetan Texture Bell Keychain with Evil Eye & Silver Hook | Good Luck Charm with Laser-Engraved Wooden Gift Box4.6 out of 5 stars 20₹299.00
--------------------------------------------------
B09T9XDQ99
Impulse rucksack bags 75 litres travel bag for men tourist bag for travel backpack for hiking trekking Bag for men camping thames blue bag with 1 Year Warranty
3,689
Impulse rucksack bags 75 litres travel bag for men tourist bag for travel backpack for hiking trekking Bag for men camping thames blue bag with 1 Year Warranty4.0 out of 5 stars 3,689₹1,139.00
--------------------------------------------------
B0F9FTG9ZS
Safari Astra Neo 8 Wheels 66cm Medium Size Check-in Trolley Bag, Hard Case Polycarbonate, 360 Degree Wheeling Luggage for Men & Women, Travel Bag, Suitcase for Travel, Champagne
1,783
Safari Astra Neo 8 Wheels 66cm Medium Size Check-in Trolley Bag, Hard Case Polycarbonate, 360 Degree Wheeling Luggage for Men & Women, Travel Bag, Suitcase for Travel, Champagne4.1 out of 5 stars 1,783₹2,199.00
--------------------------------------------------
B097RJ22Q3
Lavie Sport Polyester Lino Wheel Duffel Bag|2 Wheel Duffle Bag|Built To Last Wheels And Trolley, 63 x 30 x 32 Centimeters, Navy
13,011
Lavie Sport Polyester Lino Wheel Duffel Bag|2 Wheel Duffle Bag|Built To Last Wheels And Trolley, 63 x 30 x 32 Centimeters, Navy4.0 out of 5 stars 13,011₹987.00
--------------------------------------------------
B0CWSB5B17
Aristocrat Enigma 52 Cm Polyester Softsided Cabin Size Duffle Bag - Blue
1,576
Aristocrat Enigma 52 Cm Polyester Softsided Cabin Size Duffle Bag - Blue4.3 out of 5 stars 1,576₹449.00
--------------------------------------------------
B0FFTLRBX2
Boldfit Gym Bags for Men with Separate Shoe Compartment Unisex Duffle Bag for Carry & Travel Adjustable for Shoes Towel Duffel Sports Bag for Women & Men 20L - Black Grey
518
Boldfit Gym Bags for Men with Separate Shoe Compartment Unisex Duffle Bag for Carry & Travel Adjustable for Shoes Towel Duffel Sports Bag for Women & Men 20L - Black Grey4.2 out of 5 stars 518₹399.00
--------------------------------------------------
B0F29G1GXK
KAMILIANT by American Tourister Savvy|Trolley Bag Check-in Medium Size (70 cms) for Travel| Hard Case Polypropylene (PP) Suitcase|360° 8-Wheel Spinner Luggage Trolley|Combination Lock|Orange Pastry
2,850
KAMILIANT by American Tourister Savvy|Trolley Bag Check-in Medium Size (70 cms) for Travel| Hard Case Polypropylene (PP) Suitcase|360° 8-Wheel Spinner Luggage Trolley|Combination Lock|Orange Pastry4.1 out of 5 stars 2,850₹1,899.00
--------------------------------------------------
B0C7BM18PB
Amazon Basics Memory Foam Travel Neck Pillow with Eye Mask & Ear Plugs Combo|Ultra Soft Velvet Fabric|Ergonomically Designed for Ultimate Comfort for Air, Car, Train, Bus Travel- Black, Standard Size
10,632
Amazon Basics Memory Foam Travel Neck Pillow with Eye Mask & Ear Plugs Combo|Ultra Soft Velvet Fabric|Ergonomically Designed for Ultimate Comfort for Air, Car, Train, Bus Travel- Black, Standard Size4.2 out of 5 stars 10,632₹469.00
--------------------------------------------------
B0C8ZNNCQW
Skybags Medium Stroke Size Abs Hard Luggage (67 Cm)|Printed Luggage Trolley with 8 Spinner Wheels and in-Built Combination Lock|Unisex, Blue and White
2,580
Skybags Medium Stroke Size Abs Hard Luggage (67 Cm)|Printed Luggage Trolley with 8 Spinner Wheels and in-Built Combination Lock|Unisex, Blue and White4.2 out of 5 stars 2,580₹1,999.00
--------------------------------------------------
B0C692D6CS
PETRICE Travel Organizer Pouch Packing Cubes for Travel Essentials Toiletry Bag, Travel Luggage Organizers with Laundry Bag Travel Pouch, Packing Cubes Organizer (Grey)
2,419
PETRICE Travel Organizer Pouch Packing Cubes for Travel Essentials Toiletry Bag, Travel Luggage Organizers with Laundry Bag Travel Pouch, Packing Cubes Organizer (Grey)4.3 out of 5 stars 2,419₹389.00
--------------------------------------------------
B085LFPKQB
HORNBULL Denial Navy Leather Wallet for Men | Genuine Leather Wallet with RFID Blocking | Purse for Men
19,037
HORNBULL Denial Navy Leather Wallet for Men | Genuine Leather Wallet with RFID Blocking | Purse for Men4.2 out of 5 stars 19,037₹599.00
--------------------------------------------------
B0CF9DF3QB
Tinytot 34 Litre Korean Style School Bag Water-Resistant Laptop & Travel Backpack - Unisex Large 19 Inches Multipurpose Student Backpack for Boys & Girls, Men & Women; Black
995
Tinytot 34 Litre Korean Style School Bag Water-Resistant Laptop & Travel Backpack - Unisex Large 19 Inches Multipurpose Student Backpack for Boys & Girls, Men & Women; Black4.3 out of 5 stars 995₹1,056.00
--------------------------------------------------
B0GVSH9MJD
Aristocrat Solana Cabin Trolley Bag 53cm | Small | Hard Luggage | 8-Wheel Suitcase with Laptop Compartment for Business Travel | TSA Lock with Anti-Theft Zipper | 3 Years International Warranty (Blue)
87
Aristocrat Solana Cabin Trolley Bag 53cm | Small | Hard Luggage | 8-Wheel Suitcase with Laptop Compartment for Business Travel | TSA Lock with Anti-Theft Zipper | 3 Years International Warranty (Blue)4.4 out of 5 stars 87₹2,799.00
--------------------------------------------------
B083C76NYD
Aliston H1 Series A08/A302 digital weighing machine for Luggage weighing, Weighing scale capable of 50kg, Scale with LCD Display & Stainless steel hook.
3,203
Aliston H1 Series A08/A302 digital weighing machine for Luggage weighing, Weighing scale capable of 50kg, Scale with LCD Display & Stainless steel hook.4.1 out of 5 stars 3,203₹199.00
--------------------------------------------------
B0GPN9RZ6H
𝗪𝗢𝗢𝗠𝗭𝗬 UV Travel 𝗠𝗶𝗻𝗶 𝗙𝗼𝗹𝗱𝗶𝗻𝗴 Ultra Compact pastel 𝗨𝗺𝗯𝗿𝗲𝗹𝗹𝗮 with Case, Manual Open 𝟲 𝗥𝗶𝗯𝘀 Lightweight 𝗣𝗼𝗿𝘁𝗮𝗯𝗹𝗲, Small Sun & Rain 𝗣𝗼𝗰𝗸𝗲𝘁 𝗨𝗺𝗯𝗿𝗲𝗹𝗹𝗮 for Men and Women- Use in 𝗥𝗮𝗶𝗻 & 𝗦𝘂𝗺𝗺𝗲𝗿
402
𝗪𝗢𝗢𝗠𝗭𝗬 UV Travel 𝗠𝗶𝗻𝗶 𝗙𝗼𝗹𝗱𝗶𝗻𝗴 Ultra Compact pastel 𝗨𝗺𝗯𝗿𝗲𝗹𝗹𝗮 with Case, Manual Open 𝟲 𝗥𝗶𝗯𝘀 Lightweight 𝗣𝗼𝗿𝘁𝗮𝗯𝗹𝗲, Small Sun & Rain 𝗣𝗼𝗰𝗸𝗲𝘁 𝗨𝗺𝗯𝗿𝗲𝗹𝗹𝗮 for Men and Women- Use in 𝗥𝗮𝗶𝗻 & 𝗦𝘂𝗺𝗺𝗲𝗿4.0 out of 5 stars 402₹599.00
--------------------------------------------------
B0C4FKRWV8
Oceanevo 8 Pcs Packing Cubes for Travel, Travel Organizer Bags for Luggage, Suitcase with Toiletry Pouch and Shoe Bag - Set of 8 - Beige
1,014
Oceanevo 8 Pcs Packing Cubes for Travel, Travel Organizer Bags for Luggage, Suitcase with Toiletry Pouch and Shoe Bag - Set of 8 - Beige4.4 out of 5 stars 1,014₹569.00
--------------------------------------------------
B0F3XFTCPL
BEAUTY GIRLS BY HOTSHOT FLORAL_1594|SCHOOL BAG|TUTION BAG|COLLEGE BACKPACK|LARGE SIZE|WATER RESISTANT|19 INCH|FOR GIRLS & WOMEN|36 LITERS BACKPACK
739
BEAUTY GIRLS BY HOTSHOT FLORAL_1594|SCHOOL BAG|TUTION BAG|COLLEGE BACKPACK|LARGE SIZE|WATER RESISTANT|19 INCH|FOR GIRLS & WOMEN|36 LITERS BACKPACK4.5 out of 5 stars 739₹799.00
--------------------------------------------------
B0BW3QZBQH
Lifelong Cotton 30 L Duffle Gym Bag for Men & Women | Adjustable Shoulder Bag | Water Resistant | Sports & Travel Bag with Shoe Compartment & Side Pocket (Black & Red),48.3cm
784

# final working code

In [99]:
all_products = []

for file_name in html_files:

    # Skip non-html files
    if not file_name.endswith(".html"):
        continue

    file_path = os.path.join("raw_html", file_name)

    # Open HTML file
    with open(file_path, "r", encoding="utf-8") as file:

        html_content = file.read()

    # Create soup
    soup = BeautifulSoup(html_content, "lxml")

    # Find all products
    products = soup.find_all(
        "div",
        attrs={"data-asin": True}
    )

    print(f"\nProcessing: {file_name}")
    print(f"Products Found: {len(products)}")

    # Loop through products
    for product in products:

        try:

            # ASIN
            asin = product.get("data-asin")

            # Product Name
            name_tag = product.find(
                "div",
                class_="_cDEzb_p13n-sc-css-line-clamp-3_g3dy1"
            )

            # Backup selector
            if not name_tag:

                name_tag = product.find(
                    "div",
                    class_="_cDEzb_p13n-sc-css-line-clamp-4_2q2cc"
                )

            # Skip if no name
            if not name_tag:
                continue

            full_name = name_tag.text.strip()

            # Clean product name
            name = full_name.split(",")[0]

            name = name.split("|")[0]

            name = " ".join(name.split()[:5])

            # Reviews
            reviews_tag = product.find(
                "span",
                class_="a-size-small"
            )

            if reviews_tag:

                reviews = reviews_tag.text.strip()

                reviews = reviews.replace(",", "")

            else:

                reviews = "0"

            # Price
            price = None

            all_spans = product.find_all("span")

            for span in all_spans:

                text = span.text.strip()

                if text.startswith("₹"):

                    price = text
                    break

            # Skip if no price
            if not price:
                continue

            # Clean price
            price = (
                price.replace("₹", "")
                     .replace(",", "")
            )

            # Print extracted data
            print(asin)
            print(name)
            print(reviews)
            print(price)
            print("-" * 50)

            # Store product
            product_data = {
                "ASIN": asin,
                "Product_Name": name,
                "Reviews": int(reviews),
                "Price": float(price)
            }

            all_products.append(product_data)

        except Exception as e:

            print("Error:", e)

print("\nTotal Products Extracted:", len(all_products))

Processing: Bags, Wallets and Luggage_page1.html
Products Found: 30
B07X6GNBNT
Credit Card Bill
393124
10.00
--------------------------------------------------
B097GR45SS
Safari Pentagon Pro 8 Wheels
35066
1999.00
--------------------------------------------------
B0F67J5S83
Safari Cabin Genius Alley 55cm
6454
1299.00
--------------------------------------------------
B082F88NKP
Billebon Premium Neck Pillow for
15020
189.00
--------------------------------------------------
B0BL11Q9D3
Kamiliant American Tourister Harrier
15122
1199.00
--------------------------------------------------
B0FPDLT1CC
Trajectory Travel Neck Pillow for
19250
189.00
--------------------------------------------------
B0D8BG7S4P
Aristocrat Nova 15L Laptop Backpack
2486
299.00
--------------------------------------------------
B07CJCGM1M
American Tourister 32 Ltrs Black
34257
899.00
--------------------------------------------------
B0BK1457X3
Boldfit Shoe Bag for Travel
14852
179.00
--------------------------------------------------
B0DJ8R2XDN
Roughhouse UV Umbrella for Sun
582
329.00
--------------------------------------------------
B0F5HLYQK3
American Tourister Liftoff+
2404
3499.00
--------------------------------------------------
B07PK41FL4
GLUN® Electronic Portable Digital LED
28692
235.00
--------------------------------------------------
B079TN3GCD
WildHorn Olive Leather Men's Wallet
5351
499.00
--------------------------------------------------
B098FFTDKT
Gear Cross Training 9"/29L Large
25425
445.00
--------------------------------------------------
B09B267161
Safari Hitech Large Size 35
6052
819.00
--------------------------------------------------
B07Q822CWX
GoTrippin by Destinio Weight Machine
14853
610.00
--------------------------------------------------
B07YDGQQN5
Fur Jaden 55 LTR Rucksack
14034
795.00
--------------------------------------------------
B0C4FKHHVW
Stealodeal Brown 28 Slots Leather
2331
99.00
--------------------------------------------------
B0C5MKVBN9
Cockatoo Shoe Bag for Travel
4542
150.00
--------------------------------------------------
B07M9BRCQ5
Fur Jaden Brown Textured Leatherette
12169
649.00
--------------------------------------------------
B0F5HKFPWR
American Tourister Ivy 2.0
6904
2799.00
--------------------------------------------------
B0FCYHSSKQ
Lifelong Shoe Bags for Travel
529
199.00
--------------------------------------------------
B08P5ML6GK
WildHorn Wildhorn India Brown Leather
37916
597.00
--------------------------------------------------
B0FC6RZNDC
Aristocrat Polycarbonate Spinner Comet Cabin
2708
1409.00
--------------------------------------------------
B07MWD4D4W
M MEDLER Epoch Nylon 55
32879
599.00
--------------------------------------------------
B0C1K5S9X4
Aristocrat Medium Commander 69Cms Premium
1974
2109.00
--------------------------------------------------
B0GNSQ9RGN
Robustt Capsule Mini Foldable Travel
39
499.00
--------------------------------------------------

Processing: Bags, Wallets and Luggage_page2.html
Products Found: 30
B09RY4WHMR
Wooum Polyester Toiletry Bag for
3219
269.00
--------------------------------------------------
B0FSSMVXZ4
TrollGadgets® Guardian Bell Keychain for
649
189.00
--------------------------------------------------
B0G6CWL9HH
Catron Waterproof Makeup Pouch Bag
129
199.00
--------------------------------------------------
B08F9SFYXQ
BEAUTY GIRLS BY HOTSHOT
3898
799.00
--------------------------------------------------
B0FNDBNFDB
Safari Genius Theo 8 Wheels
1143
1399.00
--------------------------------------------------
B097JMZGP7
Safari Medium Crescent 8 Wheels
2975
2099.00
--------------------------------------------------
B0GWKCD1HN
OTTAVO Premium Guardian Bell Keychain
20
299.00
--------------------------------------------------
B09T9XDQ99
Impulse rucksack bags 75 litres
3689
1139.00
--------------------------------------------------
B0F9FTG9ZS
Safari Astra Neo 8 Wheels
1783
2199.00
--------------------------------------------------
B097RJ22Q3
Lavie Sport Polyester Lino Wheel
13011
987.00
--------------------------------------------------
B0CWSB5B17
Aristocrat Enigma 52 Cm Polyester
1576
449.00
--------------------------------------------------
B0FFTLRBX2
Boldfit Gym Bags for Men
518
399.00
--------------------------------------------------
B0F29G1GXK
KAMILIANT by American Tourister Savvy
2850
1899.00
--------------------------------------------------
B0C7BM18PB
Amazon Basics Memory Foam Travel
10632
469.00
--------------------------------------------------
B0C8ZNNCQW
Skybags Medium Stroke Size Abs
2580
1999.00
--------------------------------------------------
B0C692D6CS
PETRICE Travel Organizer Pouch Packing
2419
389.00
--------------------------------------------------
B085LFPKQB
HORNBULL Denial Navy Leather Wallet
19037
599.00
--------------------------------------------------
B0CF9DF3QB
Tinytot 34 Litre Korean Style
995
1056.00
--------------------------------------------------
B0GVSH9MJD
Aristocrat Solana Cabin Trolley Bag
87
2799.00
--------------------------------------------------
B083C76NYD
Aliston H1 Series A08/A302 digital
3203
199.00
--------------------------------------------------
B0GPN9RZ6H
𝗪𝗢𝗢𝗠𝗭𝗬 UV Travel 𝗠𝗶𝗻𝗶 𝗙𝗼𝗹𝗱𝗶𝗻𝗴
402
599.00
--------------------------------------------------
B0C4FKRWV8
Oceanevo 8 Pcs Packing Cubes
1014
569.00
--------------------------------------------------
B0F3XFTCPL
BEAUTY GIRLS BY HOTSHOT FLORAL_1594
739
799.00
--------------------------------------------------
B0BW3QZBQH
Lifelong Cotton 30 L Duffle
784
199.00
--------------------------------------------------
B0FJ672BBN
Billebon Gel Infused Memory Foam
180
449.00
--------------------------------------------------
B0F8B8Z1RL
Lyrovo Nylon 7Pcs Travel Packing
292
390.00
--------------------------------------------------
B09B29F66W
Safari Flash Medium 26L Water
6719
589.00
--------------------------------------------------
B0CY56R6V5
Boldfit Toiletry Bag for Travel
869
299.00
--------------------------------------------------
B0CJ9S6HJ6
TS WITH TECHSUN Travel Organizer
1625
499.00
--------------------------------------------------
B0DX1MF3Q4
Printed Luggage Cover for Traveling
431
499.00
--------------------------------------------------

Processing: Books_page1.html
Products Found: 30

Processing: Books_page2.html
Products Found: 30

Processing: Clothing & Accessories_page1.html
Products Found: 30
B0FRFXX2C3
KLOSIA Women's Rayon Printed Anarkali
6830
799.00
--------------------------------------------------
B06Y2FG6R7
Allen Solly Men’s Polo T‑Shirt
81308
699.00
--------------------------------------------------
B010FMJKFS
Jockey 1406 Women's High Coverage
40922
449.00
--------------------------------------------------
B07MZM26XG
Amazon Brand - Symbol Men's
38857
369.00
--------------------------------------------------
B0CKBXTPL1
TRYLO Riza T-FIT Women's Non-Padded
3059
349.00
--------------------------------------------------
B07JVPXV2Q
Van Heusen Women’s 100% Cotton
17287
399.00
--------------------------------------------------
B07HJJTHD1
Van Heusen Men's Cotton Solid
44493
699.00
--------------------------------------------------
B0DGX12XXV
SWAGR 12 Pairs Sports Cotton
5450
167.00
--------------------------------------------------
B0DNBH4W1C
boffi ... 100% Cotton Oversized
1336
288.00
--------------------------------------------------
B0GPQC7NXZ
KLOSIA Women's Printed Straight Kurta
319
699.00
--------------------------------------------------
B0DRFPPCRS
Lymio Men Shorts
822
499.00
--------------------------------------------------
B0FNWQ2D1F
Louis Luxe Womens Korean Night
789
679.00
--------------------------------------------------
B09XMV6125
Peter England Men's Regular Fit
3535
538.00
--------------------------------------------------
B09J171VHQ
Jockey 1722 Women's Wirefree Non
16182
499.00
--------------------------------------------------
B0FTX3WDH8
ANNI Designer Pure Cotton Embroidered
1164
809.00
--------------------------------------------------
B0FLK6Q7NV
Shasmi Girl's & Women's Solid
1247
529.00
--------------------------------------------------
B0G524MFS3
ANNI Designer Women's Rayon Viscose
723
762.00
--------------------------------------------------
B0FVY7GNBN
Men's Cotton Baggy Trackpants
1191
399.00
--------------------------------------------------
B0DF794BDK
Lymio Cargo for Men
629
669.00
--------------------------------------------------
B0CJFQWSYZ
Jockey 8009 Men's Super Combed
3640
849.00
--------------------------------------------------
B014213DS8
Jockey 8037 Men's Super Combed
14538
365.00
--------------------------------------------------
B071KKRY5N
Lux Cozi Men's White Round
13598
329.00
--------------------------------------------------
B0F8ZLGG8V
GoSriKi Women’s Rayon Viscose Printed
2472
652.00
--------------------------------------------------
B0FM4JKGSW
Nifty Women's Denim Stretchable High
689
729.00
--------------------------------------------------
B0FRY6CQJM
ANNI DESIGNER Women's Rayon Viscose
790
589.00
--------------------------------------------------
B012SX56OG
Jockey IC28 Men's Tactel Microfiber
13791
599.00
--------------------------------------------------
B073WCC5YL
Van Heusen Men’s Cotton Boxer
16664
470.00
--------------------------------------------------
B0F3JHWP6T
Q - RIOUS Women's Wide
1037
365.00
--------------------------------------------------
B010FMOONG
Jockey 1410 Women's Medium Coverage
31440
499.00
--------------------------------------------------

Processing: Clothing & Accessories_page2.html
Products Found: 30
B0CNKMYHN8
Boldfit Arm Sleeves for Men
2996
188.00
--------------------------------------------------
B0DP7M6DRY
Lymio Polo T Shirt for
422
389.00
--------------------------------------------------
B0D4HZ615R
PROSHARX 2 in 1 Active
2753
417.00
--------------------------------------------------
B0C3DH4XPJ
SJeware Unisex Cotton Men And
4138
116.98
--------------------------------------------------
B0BDG16KVN
ALYNE Saree Shapewear Petticoat for
5846
237.00
--------------------------------------------------
B0FNX2BNYH
Gufrina Women’s Light Rose Floral
470
448.00
--------------------------------------------------
B07JVPXVQG
Van Heusen Women’s 100% Cotton
9430
449.00
--------------------------------------------------
B073X4KMH6
Amazon Brand - Symbol Men's
19420
319.00
--------------------------------------------------
B0G3QD7W9B
Celary Women’s Cotton Blend Printed
550
599.00
--------------------------------------------------
B09CNQV8VF
Max Women's Regular Fit Mid
2183
299.00
--------------------------------------------------
B0GG459CD4
ANNI Designer Women's Rayon Viscose
265
499.00
--------------------------------------------------
B0B5GXTK4W
XYXX Men's Aero Super Combed
5520
429.00
--------------------------------------------------
B0GGHP8SR5
Klosia Women Pure Cotton Kurta
244
579.00
--------------------------------------------------
B010FPALNK
Jockey SS04 Women's High Coverage
11464
249.00
--------------------------------------------------
B09RWL4VQK
Adidas Men Ankle Length Cotton
3973
260.00
--------------------------------------------------
B0CBX5119W
U TURN Men's Casual Printed
1895
378.00
--------------------------------------------------
B0DC564YDC
ANNI Designer Women's Rayon Blend
6312
699.00
--------------------------------------------------
B08V56NV1B
XYXX Men's Uno Micromodal Solid
7948
509.00
--------------------------------------------------
B0C3HRWRBF
ZORO Men's Genuine Leather Belt
2003
227.00
--------------------------------------------------
B0CVXRBTLC
Lux Cozi Men's Half Sleeve
3270
372.00
--------------------------------------------------
B0FXRTBV8T
DEELMO Men’s Stylish Cotton Blend
1084
498.00
--------------------------------------------------
B0FNR99LWS
Bahumaan Pure Cotton Nighty for
490
785.00
--------------------------------------------------
B07X63HHPH
Levi's Men Cotton Boxer Brief
12223
433.00
--------------------------------------------------
B0D83WSP8C
Boldfit Shorts for Men Training
1208
449.00
--------------------------------------------------
B0DPL2XMTH
London Hills Women's Relaxed Fit
1216
697.00
--------------------------------------------------
B0DSW19ZZ1
GRECIILOOKS High Waist Polycotton Trousers
2205
499.00
--------------------------------------------------
B0G4DFZLQK
Arayna Women’s Cotton Printed Kurta
681
949.00
--------------------------------------------------
B0GZ7YPP71
Imsa Moda Women's Nylon Lycra
13
499.00
--------------------------------------------------
B0G7189R4V
Nermosa Women Embroidery Solid A-Line
766
799.00
--------------------------------------------------
B0DB5GZYHP
Mehrang Men's Stretchable Stretchable Formal
2295
284.00
--------------------------------------------------

Processing: Computers & Accessories_page1.html
Products Found: 30
B098NS6PVG
Ambrane Unbreakable 3A Fast Charging
36708
129.00
--------------------------------------------------
B097JJ2CK6
Safari Omega spacious/large laptop backpack
16450
599.00
--------------------------------------------------
B0DK7B3B2G
DIVIJA STORE Wood Smart Multipurpose
2080
299.00
--------------------------------------------------
B0FHWWDRRM
OnePlus Pad Lite with Biggest
705
18999.00
--------------------------------------------------
B08LHTJTBB
Dyazo 6 Angles Adjustable Aluminum
18785
339.00
--------------------------------------------------
B0CQRNWJM2
ZEBRONICS Blanc Slim Wireless Mouse
7801
349.00
--------------------------------------------------
B09VTDMRY7
FUR JADEN Anti Theft Number
15264
449.00
--------------------------------------------------
B09BFV96TS
Dyazo Water Resistant Laptop Sleeve/Laptop
22665
269.00
--------------------------------------------------
B008FWZGSG
Samsung Original Type C to
6037
380.00
--------------------------------------------------
B0BTD4S4XF
American Tourister Valex
11214
949.00
--------------------------------------------------
B01DGVKBC6
FEDUS Cat6 Ethernet Cable
19857
259.00
--------------------------------------------------
B0FGVQBNSB
Portronics Bubble 3.0 Wireless Keyboard
1229
899.00
--------------------------------------------------
B01HJI0FS2
Dell MS116 Wired Mouse
47669
269.00
--------------------------------------------------
B0DFCGB2D6
APFEN® 27W Type C to
11693
257.00
--------------------------------------------------
B0DNFSSF3F
SANDISK Ultra Dual Drive Go
4237
1949.00
--------------------------------------------------
B08VRGH6NM
Bajaj Pygmy Mini Fan 110MM
17125
899.00
--------------------------------------------------
B09QGZFBPM
Wayona Type C to Type
9629
313.98
--------------------------------------------------
B0DXQFRQZP
Oakter Mini UPS Basic for
19853
899.00
--------------------------------------------------
B0BL6S8KHM
ProElite Smart Case for iPad
4881
499.00
--------------------------------------------------
B08DDRGWTJ
XIAOMI Mi Type C Cable
37645
149.00
--------------------------------------------------
B005FYNT3G
SANDISK Cruzer Blade 32GB
273138
739.00
--------------------------------------------------
B0FJ2LY2JN
Zebronics Wattz 60CC4 Type-C to
367
169.00
--------------------------------------------------
B0FMRLJ9LF
boAt Type C to C
563
199.00
--------------------------------------------------
B0CR6JQT6F
Portronics Konnect X USB to
7651
139.00
--------------------------------------------------
B0F73SVVZH
Portronics Mport 8 Plus Dual
810
581.00
--------------------------------------------------
B0CP9NSXYJ
Arctic Fox Pureview Transparent Wireless
8653
599.00
--------------------------------------------------
B0FQCN6WG9
100W Fast Charging cable USB-A
9695
272.00
--------------------------------------------------
B0FJG2TL3C
Lenovo Idea Tab Smartchoice with
604
23999.00
--------------------------------------------------
B0C376RWQP
Zebronics-NS1000 Laptop Stand Featuring Foldable
4611
199.00
--------------------------------------------------

Processing: Computers & Accessories_page2.html
Products Found: 30
B00A0VCJPI
TP-Link TL-WA850RE N300 Wireless Range
204260
1549.00
--------------------------------------------------
B0FF4XBM5N
ZEBRONICS Wireless Mouse
3229
209.00
--------------------------------------------------
B0B296NTFV
Portronics Toad 23 Wireless Optical
15283
269.00
--------------------------------------------------
B0D7TGDMVQ
ARCTICOOL Portable Mini Fan -
1692
799.00
--------------------------------------------------
B0D3TX2SDB
Gaiatop Mini Portable Fan
5147
899.00
--------------------------------------------------
B0BBQK41CV
Zebronics 200HB USB 3.0 4
3167
219.00
--------------------------------------------------
B0BG62HMDJ
Cablet 2.5 Inch SATA USB
5772
299.00
--------------------------------------------------
B0GZVBHQC7
DRIFTX COMBO Portable Hand Fan
6
499.00
--------------------------------------------------
B08PFSZ7FH
STRIFF Laptop Tabletop Stand
3184
199.00
--------------------------------------------------
B094QZLJQ6
Seagate One Touch 2Tb External
21048
12999.00
--------------------------------------------------
B0DV5C5FR2
Gesto Portable Fan Rechargeable with
1089
599.00
--------------------------------------------------
B0CHBHYLLR
Honeywell 7-in-1 TypeC Docking Station
1174
1999.00
--------------------------------------------------
B077T3BG5L
Zebronics ZEB-KM2100 Multimedia USB Keyboard
45517
249.00
--------------------------------------------------
B0DXV31MLB
HAMMER 100W 5A USB to
2269
179.00
--------------------------------------------------
B0D8KQK2CY
ZEBRONICS MSP-X1 Mouse Pad
3511
84.00
--------------------------------------------------
B0BKPMD1BN
Robustrion Tempered Glass for iPad
3510
399.00
--------------------------------------------------
B0GP83XVS5
TECHNOVIBES Foldable Study Table/Bed Table/Foldable
4802
899.00
--------------------------------------------------
B08ZJG6TVT
Seagate Expansion 2TB External HDD
32612
12699.00
--------------------------------------------------
B0D18192T2
Logitech M186 Wireless Mouse
4066
599.00
--------------------------------------------------
B08CYNJ5KY
HP 682 Black Original Ink
8050
1025.00
--------------------------------------------------
B08CF3D7QR
Portronics Konnect L POR-1081 Fast
35214
159.00
--------------------------------------------------
B0B9LDCX89
STRIFF Mpad Mouse Mat 230X190X3mm
16687
99.00
--------------------------------------------------
B0C2KRGMHC
EVM EnStore 8GB USB 2.0
3081
399.00
--------------------------------------------------
B0DG5DL8TM
EVM EnX 64GB USB 3.2
106
699.00
--------------------------------------------------
B07BZ5VC4H
Safari 45L Expandable Overnighter Casual
10289
1839.00
--------------------------------------------------
B0F2FYKDS4
HAMMER 27W Type-C to Lightning
1158
199.00
--------------------------------------------------
B0CP2K2XN8
SaleOn 8.3x5 Inch Tech Pouch
3106
293.00
--------------------------------------------------
B07JPX9CR7
Dell WM118 Wireless Mouse
16520
549.00
--------------------------------------------------
B093QCY6YJ
ZEBRONICS ZEB-USB150WF1 WiFi USB Mini
7948
199.00
--------------------------------------------------

Processing: Electronics_page1.html
Products Found: 30
B0GWLJL55D
OnePlus Nord CE6
25
32998.00
--------------------------------------------------
B0GS5Y7QBF
REDMI A7 Pro 5G (Mist
274
11999.00
--------------------------------------------------
B0FMDL81GS
OnePlus Nord Buds 3r TWS
44259
1799.00
--------------------------------------------------
B098NS6PVG
Ambrane Unbreakable 3A Fast Charging
36708
129.00
--------------------------------------------------
B0GRBBPBGQ
OnePlus Nord 6
689
38998.00
--------------------------------------------------
B0DCZ3WDTB
Xiaomi Power Bank 4i 20000mAh
10002
1799.00
--------------------------------------------------
B0FN7RN9TH
Samsung Galaxy M17 5G Mobile
2459
14499.00
--------------------------------------------------
B0FBRGKXHG
OnePlus Bullets Wireless Z3 in-Ear
230008
1799.00
--------------------------------------------------
B0DDHM6D3L
Portronics Conch Theta C in
8823
279.00
--------------------------------------------------
B0D2R2MXXJ
Samsung Original 25W USB Type-C
19976
750.00

In [100]:
df = pd.DataFrame(all_products)

df.head()

         ASIN                          Product_Name  Reviews   Price
0  B07X6GNBNT                      Credit Card Bill   393124    10.0
1  B097GR45SS          Safari Pentagon Pro 8 Wheels    35066  1999.0
2  B0F67J5S83        Safari Cabin Genius Alley 55cm     6454  1299.0
3  B082F88NKP      Billebon Premium Neck Pillow for    15020   189.0
4  B0BL11Q9D3  Kamiliant American Tourister Harrier    15122  1199.0

In [101]:
df = pd.DataFrame(all_products)

df.to_csv(
    "amazon_products.csv",
    index=False,
    encoding="utf-8"
)

In [102]:
pd.DataFrame(all_products)

           ASIN                          Product_Name  Reviews   Price
0    B07X6GNBNT                      Credit Card Bill   393124    10.0
1    B097GR45SS          Safari Pentagon Pro 8 Wheels    35066  1999.0
2    B0F67J5S83        Safari Cabin Genius Alley 55cm     6454  1299.0
3    B082F88NKP      Billebon Premium Neck Pillow for    15020   189.0
4    B0BL11Q9D3  Kamiliant American Tourister Harrier    15122  1199.0
..          ...                                   ...      ...     ...
540  B09PLKQYDR         PSS PS5 Controller Thumb Grip      246   222.0
541  B0BHH2VYBW                                UniPin      135   250.0
542  B0D6RLY5YT        FITVERT PS5 Thumb Grips Rocker      130   179.0
543  B0C5C9QVQX                             Decathlon       32  1000.0
544  B0FB5NRFWS    Meyaar G.S.TAC PS5 Controller Skin       32   998.0

[545 rows x 4 columns]